card_dict = {
    "A_Thousand_Cuts": [ "A Thousand Cuts", "AThousandCuts", "凌迟" ],
    "Accuracy": [ "Accuracy", "精准" ],
    "Acrobatics": [ "Acrobatics", "杂技" ],
    "Adrenaline": [ "Adrenaline", "肾上腺素" ],
    "After_Image": [ "After Image", "AfterImage", "余像" ],
    "Aggregate": [ "Aggregate", "汇集" ],
    "Alchemize": [ "Alchemize", "炼制药水" ],
    "All-Out_Attack": [ "All-Out Attack", "AllOutAttack", "全力攻击" ],
    "All_for_One": [ "All for One", "AllforOne", "万物一心" ],
    "Alpha": [ "Alpha", "阿尔法" ],
    "Amplify": [ "Amplify", "增幅" ],
    "Anger": [ "Anger", "愤怒" ],
    "Apotheosis": [ "Apotheosis", "神化" ],
    "Apparition": [ "Apparition", "灵体" ],
    "Armaments": [ "Armaments", "武装" ],
    "Ascender's_Bane": [ "Ascender's Bane", "AscendersBane", "进阶之灾" ],
    "Auto-Shields": [ "Auto-Shields", "AutoShields", "自动护盾" ],
    "Backflip": [ "Backflip", "后空翻" ],
    "Backstab": [ "Backstab", "背刺" ],
    "Ball_Lightning": [ "Ball Lightning", "BallLightning", "球状闪电" ],
    "Bandage_Up": [ "Bandage Up", "BandageUp", "包扎" ],
    "Bane": [ "Bane", "灾祸" ],
    "Barrage": [ "Barrage", "弹幕齐射" ],
    "Barricade": [ "Barricade", "壁垒" ],
    "Bash": [ "Bash", "痛击" ],
    "Battle_Hymn": [ "Battle Hymn", "BattleHymn", "战歌" ],
    "Battle_Trance": [ "Battle Trance", "BattleTrance", "战斗专注" ],
    "Beam_Cell": [ "Beam Cell", "BeamCell", "光束射线" ],
    "Berserk": [ "Berserk", "狂暴" ],
    "Beta": [ "Beta", "贝塔" ],
    "Biased_Cognition": [ "Biased Cognition", "BiasedCognition", "偏差认知" ],
    "Bite": [ "Bite", "噬咬" ],
    "Blade_Dance": [ "Blade Dance", "BladeDance", "刀刃之舞" ],
    "Blasphemy": [ "Blasphemy", "渎神" ],
    "Blind": [ "Blind", "致盲" ],
    "Blizzard": [ "Blizzard", "暴雪" ],
    "Blood_for_Blood": [ "Blood for Blood", "BloodforBlood", "以血还血" ],
    "Bloodletting": [ "Bloodletting", "放血" ],
    "Bludgeon": [ "Bludgeon", "重锤" ],
    "Blur": [ "Blur", "残影" ],
    "Body_Slam": [ "Body Slam", "BodySlam", "全身撞击" ],
    "Boot_Sequence": [ "Boot Sequence", "BootSequence", "启动流程" ],
    "Bouncing_Flask": [ "Bouncing Flask", "BouncingFlask", "弹跳药瓶" ],
    "Bowling_Bash": [ "Bowling Bash", "BowlingBash", "碰撞连击" ],
    "Brilliance": [ "Brilliance", "光辉" ],
    "Brutality": [ "Brutality", "残暴" ],
    "Buffer": [ "Buffer", "缓冲" ],
    "Bullet_Time": [ "Bullet Time", "BulletTime", "子弹时间" ],
    "Bullseye": [ "Bullseye", "瞄准靶心" ],
    "Burn": [ "Burn", "灼伤" ],
    "Burning_Pact": [ "Burning Pact", "BurningPact", "燃烧契约" ],
    "Burst": [ "Burst", "爆发" ],
    "Calculated_Gamble": [ "Calculated Gamble", "CalculatedGamble", "计算下注" ],
    "Caltrops": [ "Caltrops", "铁蒺藜" ],
    "Capacitor": [ "Capacitor", "扩容" ],
    "Carnage": [ "Carnage", "残杀" ],
    "Carve_Reality": [ "Carve Reality", "CarveReality", "改造现实" ],
    "Catalyst": [ "Catalyst", "催化剂" ],
    "Chaos": [ "Chaos", "混沌" ],
    "Charge_Battery": [ "Charge Battery", "ChargeBattery", "充电" ],
    "Chill": [ "Chill", "冰寒" ],
    "Choke": [ "Choke", "勒脖" ],
    "Chrysalis": [ "Chrysalis", "结茧" ],
    "Clash": [ "Clash", "交锋" ],
    "Claw": [ "Claw", "爪击" ],
    "Cleave": [ "Cleave", "顺劈斩" ],
    "Cloak_and_Dagger": [ "Cloak and Dagger", "CloakandDagger", "斗篷与匕首" ],
    "Clothesline": [ "Clothesline", "金刚臂" ],
    "Clumsy": [ "Clumsy", "笨拙" ],
    "Cold_Snap": [ "Cold Snap", "ColdSnap", "寒流" ],
    "Collect": [ "Collect", "收集" ],
    "Combust": [ "Combust", "自燃" ],
    "Compile_Driver": [ "Compile Driver", "CompileDriver", "编译冲击" ],
    "Concentrate": [ "Concentrate", "全神贯注" ],
    "Conclude": [ "Conclude", "结末" ],
    "Conjure_Blade": [ "Conjure Blade", "ConjureBlade", "聚能成刃" ],
    "Consecrate": [ "Consecrate", "供奉" ],
    "Consume": [ "Consume", "耗尽" ],
    "Coolheaded": [ "Coolheaded", "冷静头脑" ],
    "Core_Surge": [ "Core Surge", "CoreSurge", "核心电泳" ],
    "Corpse_Explosion": [ "Corpse Explosion", "CorpseExplosion", "尸爆术" ],
    "Corruption": [ "Corruption", "腐化" ],
    "Creative_AI": [ "Creative AI", "CreativeAI", "创造性AI" ],
    "Crescendo": [ "Crescendo", "渐强" ],
    "Crippling_Cloud": [ "Crippling Cloud", "CripplingCloud", "致残毒云" ],
    "Crush_Joints": [ "Crush Joints", "CrushJoints", "粉碎关节" ],
    "Curse_of_the_Bell": [ "Curse of the Bell", "CurseoftheBell", "铃铛的诅咒" ],
    "Cut_Through_Fate": [ "Cut Through Fate", "CutThroughFate", "斩破命运" ],
    "Dagger_Spray": [ "Dagger Spray", "DaggerSpray", "匕首雨" ],
    "Dagger_Throw": [ "Dagger Throw", "DaggerThrow", "投掷匕首" ],
    "Dark_Embrace": [ "Dark Embrace", "DarkEmbrace", "黑暗之拥" ],
    "Dark_Shackles": [ "Dark Shackles", "DarkShackles", "黑暗镣铐" ],
    "Darkness": [ "Darkness", "漆黑" ],
    "Dash": [ "Dash", "冲刺" ],
    "Dazed": [ "Dazed", "晕眩" ],
    "Deadly_Poison": [ "Deadly Poison", "DeadlyPoison", "致命毒药" ],
    "Decay": [ "Decay", "腐朽" ],
    "Deceive_Reality": [ "Deceive Reality", "DeceiveReality", "欺瞒现实" ],
    "Deep_Breath": [ "Deep Breath", "DeepBreath", "深呼吸" ],
    "Defend_(Defect)": [ "Defend", "防御" ],
    "Defend_(Ironclad)": [ "Defend", "防御" ],
    "Defend_(Silent)": [ "Defend", "防御" ],
    "Defend_(Watcher)": [ "Defend", "防御" ],
    "Deflect": [ "Deflect", "偏折" ],
    "Defragment": [ "Defragment", "碎片整理" ],
    "Demon_Form": [ "Demon Form", "DemonForm", "恶魔形态" ],
    "Deus_Ex_Machina": [ "Deus Ex Machina", "DeusExMachina", "机械降神" ],
    "Deva_Form": [ "Deva Form", "DevaForm", "天人形态" ],
    "Devotion": [ "Devotion", "虔信" ],
    "Die_Die_Die": [ "Die Die Die", "DieDieDie", "死吧死吧死吧" ],
    "Disarm": [ "Disarm", "缴械" ],
    "Discovery": [ "Discovery", "发现" ],
    "Distraction": [ "Distraction", "声东击西" ],
    "Dodge_and_Roll": [ "Dodge and Roll", "DodgeandRoll", "闪躲翻滚" ],
    "Doom_and_Gloom": [ "Doom and Gloom", "DoomandGloom", "愁云惨淡" ],
    "Doppelganger": [ "Doppelganger", "双重存在" ],
    "Double_Energy": [ "Double Energy", "DoubleEnergy", "双倍能量" ],
    "Double_Tap": [ "Double Tap", "DoubleTap", "双发" ],
    "Doubt": [ "Doubt", "疑虑" ],
    "Dramatic_Entrance": [ "Dramatic Entrance", "DramaticEntrance", "闪亮登场" ],
    "Dropkick": [ "Dropkick", "飞身踢" ],
    "Dual_Wield": [ "Dual Wield", "DualWield", "双持" ],
    "Dualcast": [ "Dualcast", "双重释放" ],
    "Echo_Form": [ "Echo Form", "EchoForm", "回响形态" ],
    "Electrodynamics": [ "Electrodynamics", "电动力学" ],
    "Empty_Body": [ "Empty Body", "EmptyBody", "化体为空" ],
    "Empty_Fist": [ "Empty Fist", "EmptyFist", "化拳为空" ],
    "Empty_Mind": [ "Empty Mind", "EmptyMind", "化智为空" ],
    "Endless_Agony": [ "Endless Agony", "EndlessAgony", "无尽苦痛" ],
    "Enlightenment": [ "Enlightenment", "开悟" ],
    "Entrench": [ "Entrench", "巩固" ],
    "Envenom": [ "Envenom", "涂毒" ],
    "Equilibrium": [ "Equilibrium", "均衡" ],
    "Eruption": [ "Eruption", "暴怒" ],
    "Escape_Plan": [ "Escape Plan", "EscapePlan", "逃脱计划" ],
    "Establishment": [ "Establishment", "确立基础" ],
    "Evaluate": [ "Evaluate", "评估" ],
    "Eviscerate": [ "Eviscerate", "内脏切除" ],
    "Evolve": [ "Evolve", "进化" ],
    "Exhume": [ "Exhume", "发掘" ],
    "Expertise": [ "Expertise", "独门技术" ],
    "Expunger": [ "Expunger", "灭除之刃" ],
    "Fasting": [ "Fasting", "斋戒" ],
    "Fear_No_Evil": [ "Fear No Evil", "FearNoEvil", "不惧妖邪" ],
    "Feed": [ "Feed", "狂宴" ],
    "Feel_No_Pain": [ "Feel No Pain", "FeelNoPain", "无惧疼痛" ],
    "Fiend_Fire": [ "Fiend Fire", "FiendFire", "恶魔之焰" ],
    "Finesse": [ "Finesse", "妙计" ],
    "Finisher": [ "Finisher", "终结技" ],
    "Fire_Breathing": [ "Fire Breathing", "FireBreathing", "火焰吐息" ],
    "Fission": [ "Fission", "裂变" ],
    "Flame_Barrier": [ "Flame Barrier", "FlameBarrier", "火焰屏障" ],
    "Flash_of_Steel": [ "Flash of Steel", "FlashofSteel", "亮剑" ],
    "Flechettes": [ "Flechettes", "飞镖" ],
    "Flex": [ "Flex", "活动肌肉" ],
    "Flurry_of_Blows": [ "Flurry of Blows", "FlurryofBlows", "疾风连击" ],
    "Flying_Knee": [ "Flying Knee", "FlyingKnee", "飞膝" ],
    "Flying_Sleeves": [ "Flying Sleeves", "FlyingSleeves", "流云飞袖" ],
    "Follow-Up": [ "Follow-Up", "FollowUp", "追击" ],
    "Footwork": [ "Footwork", "灵动步法" ],
    "Force_Field": [ "Force Field", "ForceField", "力场" ],
    "Foreign_Influence": [ "Foreign Influence", "ForeignInfluence", "他山之石" ],
    "Foresight": [ "Foresight", "先见之明" ],
    "Forethought": [ "Forethought", "预谋" ],
    "FTL": [ "FTL", "超越光速" ],
    "Fusion": [ "Fusion", "聚变" ],
    "Genetic_Algorithm": [ "Genetic Algorithm", "GeneticAlgorithm", "遗传算法" ],
    "Ghostly_Armor": [ "Ghostly Armor", "GhostlyArmor", "幽灵铠甲" ],
    "Glacier": [ "Glacier", "冰川" ],
    "Glass_Knife": [ "Glass Knife", "GlassKnife", "玻璃刀刃" ],
    "Go_for_the_Eye": [ "Go for the Eye", "GofortheEye", "眼部攻击" ],
    "Good_Instincts": [ "Good Instincts", "GoodInstincts", "优秀直觉" ],
    "Grand_Finale": [ "Grand Finale", "GrandFinale", "华丽收场" ],
    "Halt": [ "Halt", "停顿" ],
    "Hand_of_Greed": [ "Hand of Greed", "HandofGreed", "贪婪之手" ],
    "Havoc": [ "Havoc", "破灭" ],
    "Headbutt": [ "Headbutt", "头槌" ],
    "Heatsinks": [ "Heatsinks", "散热片" ],
    "Heavy_Blade": [ "Heavy Blade", "HeavyBlade", "重刃" ],
    "Heel_Hook": [ "Heel Hook", "HeelHook", "足跟勾" ],
    "Hello_World": [ "Hello World", "HelloWorld", "你好，世界" ],
    "Hemokinesis": [ "Hemokinesis", "御血术" ],
    "Hologram": [ "Hologram", "全息影像" ],
    "Hyperbeam": [ "Hyperbeam", "超能光束" ],
    "Immolate": [ "Immolate", "燔祭" ],
    "Impatience": [ "Impatience", "急躁" ],
    "Impervious": [ "Impervious", "岿然不动" ],
    "Indignation": [ "Indignation", "义愤填膺" ],
    "Infernal_Blade": [ "Infernal Blade", "InfernalBlade", "地狱之刃" ],
    "Infinite_Blades": [ "Infinite Blades", "InfiniteBlades", "无限刀刃" ],
    "Inflame": [ "Inflame", "燃烧" ],
    "Injury": [ "Injury", "受伤" ],
    "Inner_Peace": [ "Inner Peace", "InnerPeace", "内心宁静" ],
    "Insight": [ "Insight", "洞见" ],
    "Intimidate": [ "Intimidate", "威吓" ],
    "Iron_Wave": [ "Iron Wave", "IronWave", "铁斩波" ],
    "J.A.X.": [ "J.A.X.", "JAX", "强化剂" ],
    "Jack_of_All_Trades": [ "Jack of All Trades", "JackofAllTrades", "花样百出" ],
    "Judgment": [ "Judgment", "审判" ],
    "Juggernaut": [ "Juggernaut", "势不可当" ],
    "Just_Lucky": [ "Just Lucky", "JustLucky", "幸运一击" ],
    "Leap": [ "Leap", "飞跃" ],
    "Leg_Sweep": [ "Leg Sweep", "LegSweep", "扫腿" ],
    "Lesson_Learned": [ "Lesson Learned", "LessonLearned", "勤学精进" ],
    "Like_Water": [ "Like Water", "LikeWater", "如水" ],
    "Limit_Break": [ "Limit Break", "LimitBreak", "突破极限" ],
    "Loop": [ "Loop", "循环" ],
    "Machine_Learning": [ "Machine Learning", "MachineLearning", "机器学习" ],
    "Madness": [ "Madness", "疯狂" ],
    "Magnetism": [ "Magnetism", "磁力" ],
    "Malaise": [ "Malaise", "萎靡" ],
    "Master_of_Strategy": [ "Master of Strategy", "MasterofStrategy", "战略大师" ],
    "Master_Reality": [ "Master Reality", "MasterReality", "操控现实" ],
    "Masterful_Stab": [ "Masterful Stab", "MasterfulStab", "精巧刺击" ],
    "Mayhem": [ "Mayhem", "乱战" ],
    "Meditate": [ "Meditate", "冥想" ],
    "Melter": [ "Melter", "熔化" ],
    "Mental_Fortress": [ "Mental Fortress", "MentalFortress", "心灵堡垒" ],
    "Metallicize": [ "Metallicize", "金属化" ],
    "Metamorphosis": [ "Metamorphosis", "羽化" ],
    "Meteor_Strike": [ "Meteor Strike", "MeteorStrike", "陨石打击" ],
    "Mind_Blast": [ "Mind Blast", "MindBlast", "心灵震慑" ],
    "Miracle": [ "Miracle", "奇迹" ],
    "Multi-Cast": [ "Multi-Cast", "MultiCast", "多重释放" ],
    "Necronomicurse": [ "Necronomicurse", "死灵诅咒" ],
    "Neutralize": [ "Neutralize", "中和" ],
    "Nightmare": [ "Nightmare", "夜魇" ],
    "Nirvana": [ "Nirvana", "涅槃" ],
    "Normality": [ "Normality", "凡庸" ],
    "Noxious_Fumes": [ "Noxious Fumes", "NoxiousFumes", "毒雾" ],
    "Offering": [ "Offering", "祭品" ],
    "Omega": [ "Omega", "欧米伽" ],
    "Omniscience": [ "Omniscience", "通晓万物" ],
    "Outmaneuver": [ "Outmaneuver", "抢占先机" ],
    "Overclock": [ "Overclock", "超频" ],
    "Pain": [ "Pain", "疼痛" ],
    "Panacea": [ "Panacea", "万能药" ],
    "Panache": [ "Panache", "神气制胜" ],
    "Panic_Button": [ "Panic Button", "PanicButton", "紧急按钮" ],
    "Parasite": [ "Parasite", "寄生" ],
    "Perfected_Strike": [ "Perfected Strike", "PerfectedStrike", "完美打击" ],
    "Perseverance": [ "Perseverance", "坚韧" ],
    "Phantasmal_Killer": [ "Phantasmal Killer", "PhantasmalKiller", "幻影杀手" ],
    "Piercing_Wail": [ "Piercing Wail", "PiercingWail", "尖啸" ],
    "Poisoned_Stab": [ "Poisoned Stab", "PoisonedStab", "带毒刺击" ],
    "Pommel_Strike": [ "Pommel Strike", "PommelStrike", "剑柄打击" ],
    "Power_Through": [ "Power Through", "PowerThrough", "硬撑" ],
    "Pray": [ "Pray", "祈祷" ],
    "Predator": [ "Predator", "猎杀者" ],
    "Prepared": [ "Prepared", "早有准备" ],
    "Pressure_Points": [ "Pressure Points", "PressurePoints", "点穴" ],
    "Pride": [ "Pride", "傲慢" ],
    "Prostrate": [ "Prostrate", "五体投地" ],
    "Protect": [ "Protect", "护身" ],
    "Pummel": [ "Pummel", "连续拳" ],
    "Purity": [ "Purity", "净化" ],
    "Quick_Slash": [ "Quick Slash", "QuickSlash", "快斩" ],
    "Rage": [ "Rage", "狂怒" ],
    "Ragnarok": [ "Ragnarok", "诸神之黄昏" ],
    "Rainbow": [ "Rainbow", "彩虹" ],
    "Rampage": [ "Rampage", "暴走" ],
    "Reach_Heaven": [ "Reach Heaven", "ReachHeaven", "立地升天" ],
    "Reaper": [ "Reaper", "死亡收割" ],
    "Reboot": [ "Reboot", "重启" ],
    "Rebound": [ "Rebound", "弹回" ],
    "Reckless_Charge": [ "Reckless Charge", "RecklessCharge", "无谋冲锋" ],
    "Recursion": [ "Recursion", "递归" ],
    "Recycle": [ "Recycle", "回收" ],
    "Reflex": [ "Reflex", "本能反应" ],
    "Regret": [ "Regret", "悔恨" ],
    "Reinforced_Body": [ "Reinforced Body", "ReinforcedBody", "硬化机体" ],
    "Reprogram": [ "Reprogram", "重编程" ],
    "Riddle_with_Holes": [ "Riddle with Holes", "RiddlewithHoles", "千穿百刺" ],
    "Rip_and_Tear": [ "Rip and Tear", "RipandTear", "狂乱撕扯" ],
    "Ritual_Dagger": [ "Ritual Dagger", "RitualDagger", "仪式匕首" ],
    "Rupture": [ "Rupture", "撕裂" ],
    "Rushdown": [ "Rushdown", "猛虎下山" ],
    "Sadistic_Nature": [ "Sadistic Nature", "SadisticNature", "残虐天性" ],
    "Safety": [ "Safety", "平安" ],
    "Sanctity": [ "Sanctity", "圣洁" ],
    "Sands_of_Time": [ "Sands of Time", "SandsofTime", "时之沙" ],
    "Sash_Whip": [ "Sash Whip", "SashWhip", "腰带抽打" ],
    "Scrape": [ "Scrape", "刮削" ],
    "Scrawl": [ "Scrawl", "潦草急就" ],
    "Searing_Blow": [ "Searing Blow", "SearingBlow", "灼热攻击" ],
    "Second_Wind": [ "Second Wind", "SecondWind", "重振精神" ],
    "Secret_Technique": [ "Secret Technique", "SecretTechnique", "秘密技法" ],
    "Secret_Weapon": [ "Secret Weapon", "SecretWeapon", "秘密武器" ],
    "Seeing_Red": [ "Seeing Red", "SeeingRed", "盛怒" ],
    "Seek": [ "Seek", "搜寻" ],
    "Self_Repair": [ "Self Repair", "SelfRepair", "自我修复" ],
    "Sentinel": [ "Sentinel", "哨卫" ],
    "Setup": [ "Setup", "部署" ],
    "Sever_Soul": [ "Sever Soul", "SeverSoul", "断魂斩" ],
    "Shame": [ "Shame", "羞耻" ],
    "Shiv": [ "Shiv", "小刀" ],
    "Shockwave": [ "Shockwave", "震荡波" ],
    "Shrug_It_Off": [ "Shrug It Off", "ShrugItOff", "耸肩无视" ],
    "Signature_Move": [ "Signature Move", "SignatureMove", "招牌技" ],
    "Simmering_Fury": [ "Simmering Fury", "SimmeringFury", "怒火中烧" ],
    "Skewer": [ "Skewer", "串刺" ],
    "Skim": [ "Skim", "快速检索" ],
    "Slice": [ "Slice", "切割" ],
    "Slimed": [ "Slimed", "粘液" ],
    "Smite": [ "Smite", "惩恶" ],
    "Sneaky_Strike": [ "Sneaky Strike", "SneakyStrike", "隐秘打击" ],
    "Spirit_Shield": [ "Spirit Shield", "SpiritShield", "精神护盾" ],
    "Spot_Weakness": [ "Spot Weakness", "SpotWeakness", "观察弱点" ],
    "Stack": [ "Stack", "堆栈" ],
    "Static_Discharge": [ "Static Discharge", "StaticDischarge", "静电释放" ],
    "Steam_Barrier": [ "Steam Barrier", "SteamBarrier", "蒸汽护壁" ],
    "Storm": [ "Storm", "雷暴" ],
    "Storm_of_Steel": [ "Storm of Steel", "StormofSteel", "钢铁风暴" ],
    "Streamline": [ "Streamline", "精简改良" ],
    "Strike_(Defect)": [ "Strike", "打击" ],
    "Strike_(Ironclad)": [ "Strike", "打击" ],
    "Strike_(Silent)": [ "Strike", "打击" ],
    "Strike_(Watcher)": [ "Strike", "打击" ],
    "Study": [ "Study", "研习" ],
    "Sucker_Punch": [ "Sucker Punch", "SuckerPunch", "突然一拳" ],
    "Sunder": [ "Sunder", "分离" ],
    "Survivor": [ "Survivor", "生存者" ],
    "Sweeping_Beam": [ "Sweeping Beam", "SweepingBeam", "扫荡射线" ],
    "Swift_Strike": [ "Swift Strike", "SwiftStrike", "迅捷打击" ],
    "Swivel": [ "Swivel", "旋身" ],
    "Sword_Boomerang": [ "Sword Boomerang", "SwordBoomerang", "飞剑回旋镖" ],
    "Tactician": [ "Tactician", "战术大师" ],
    "Talk_to_the_Hand": [ "Talk to the Hand", "TalktotheHand", "以手拒之" ],
    "Tantrum": [ "Tantrum", "发泄" ],
    "Tempest": [ "Tempest", "暴风雨" ],
    "Terror": [ "Terror", "恐怖" ],
    "The_Bomb": [ "The Bomb", "TheBomb", "炸弹" ],
    "Thinking_Ahead": [ "Thinking Ahead", "ThinkingAhead", "深谋远虑" ],
    "Third_Eye": [ "Third Eye", "ThirdEye", "天眼" ],
    "Through_Violence": [ "Through Violence", "ThroughViolence", "以暴制暴" ],
    "Thunder_Strike": [ "Thunder Strike", "ThunderStrike", "雷霆打击" ],
    "Thunderclap": [ "Thunderclap", "闪电霹雳" ],
    "Tools_of_the_Trade": [ "Tools of the Trade", "ToolsoftheTrade", "必备工具" ],
    "Tranquility": [ "Tranquility", "安宁" ],
    "Transmutation": [ "Transmutation", "转化" ],
    "Trip": [ "Trip", "绊倒" ],
    "True_Grit": [ "True Grit", "TrueGrit", "坚毅" ],
    "TURBO": [ "TURBO", "内核加速" ],
    "Twin_Strike": [ "Twin Strike", "TwinStrike", "双重打击" ],
    "Unload": [ "Unload", "乾坤一掷" ],
    "Uppercut": [ "Uppercut", "上勾拳" ],
    "Vault": [ "Vault", "腾跃" ],
    "Vigilance": [ "Vigilance", "警惕" ],
    "Violence": [ "Violence", "暴力" ],
    "Void": [ "Void", "虚空" ],
    "Wallop": [ "Wallop", "当头棒喝" ],
    "Warcry": [ "Warcry", "战吼" ],
    "Wave_of_the_Hand": [ "Wave of the Hand", "WaveoftheHand", "摆手" ],
    "Weave": [ "Weave", "迂回" ],
    "Well-Laid_Plans": [ "Well-Laid Plans", "WellLaidPlans", "计划妥当" ],
    "Wheel_Kick": [ "Wheel Kick", "WheelKick", "回环踢" ],
    "Whirlwind": [ "Whirlwind", "旋风斩" ],
    "White_Noise": [ "White Noise", "WhiteNoise", "白噪声" ],
    "Wild_Strike": [ "Wild Strike", "WildStrike", "狂野打击" ],
    "Windmill_Strike": [ "Windmill Strike", "WindmillStrike", "旋转打击" ],
    "Wish": [ "Wish", "许愿" ],
    "Worship": [ "Worship", "敬拜" ],
    "Wound": [ "Wound", "伤口" ],
    "Wraith_Form": [ "Wraith Form", "WraithForm", "幽魂形态" ],
    "Wreath_of_Flame": [ "Wreath of Flame", "WreathofFlame", "火焰纹" ],
    "Writhe": [ "Writhe", "苦恼" ],
    "Zap": [ "Zap", "电击" ],
}
