card_dict = {
    "StS2 Beta-Colorless-MadScience": [ "Mad Science", "MadScience", "疯狂科学" ],
    "StS2 Beta-Colorless-MadSciencePlus": [ "Mad Science+", "MadScience+", "疯狂科学+" ],
    "StS2 Colorless-Abundance": [ "Abundance", "富足" ],
    "StS2 Colorless-AbundancePlus": [ "Abundance+", "富足+" ],
    "StS2 Colorless-Alchemize": [ "Alchemize", "炼制药水" ],
    "StS2 Colorless-AlchemizePlus": [ "Alchemize+", "炼制药水+" ],
    "StS2 Colorless-Anointed": [ "Anointed", "天选" ],
    "StS2 Colorless-AnointedPlus": [ "Anointed+", "天选+" ],
    "StS2 Colorless-Apotheosis": [ "Apotheosis", "神化" ],
    "StS2 Colorless-ApotheosisPlus": [ "Apotheosis+", "神化+" ],
    "StS2 Colorless-Apparition": [ "Apparition", "灵体" ],
    "StS2 Colorless-ApparitionPlus": [ "Apparition+", "灵体+" ],
    "StS2 Colorless-Automation": [ "Automation", "自动化" ],
    "StS2 Colorless-AutomationPlus": [ "Automation+", "自动化+" ],
    "StS2 Colorless-BeaconOfHope": [ "Beacon of Hope", "BeaconofHope", "希望灯塔" ],
    "StS2 Colorless-BeaconOfHopePlus": [ "Beacon of Hope+", "BeaconofHope+", "希望灯塔+" ],
    "StS2 Colorless-BeatDown": [ "Beat Down", "BeatDown", "狠揍" ],
    "StS2 Colorless-BeatDownPlus": [ "Beat Down+", "BeatDown+", "狠揍+" ],
    "StS2 Colorless-Beckon": [ "Beckon", "呼唤" ],
    "StS2 Colorless-BelieveInYou": [ "Believe in You", "BelieveinYou", "相信着你" ],
    "StS2 Colorless-BelieveInYouPlus": [ "Believe in You+", "BelieveinYou+", "相信着你+" ],
    "StS2 Colorless-Bolas": [ "Bolas", "流星锤" ],
    "StS2 Colorless-BolasPlus": [ "Bolas+", "流星锤+" ],
    "StS2 Colorless-BrightestFlame": [ "Brightest Flame", "BrightestFlame", "至亮之焰" ],
    "StS2 Colorless-BrightestFlamePlus": [ "Brightest Flame+", "BrightestFlame+", "至亮之焰+" ],
    "StS2 Colorless-Burn": [ "Burn", "灼伤" ],
    "StS2 Colorless-ByrdSwoop": [ "Byrd Swoop", "ByrdSwoop", "异鸟扑击" ],
    "StS2 Colorless-ByrdSwoopPlus": [ "Byrd Swoop+", "ByrdSwoop+", "异鸟扑击+" ],
    "StS2 Colorless-Calamity": [ "Calamity", "劫难" ],
    "StS2 Colorless-CalamityPlus": [ "Calamity+", "劫难+" ],
    "StS2 Colorless-Caltrops": [ "Caltrops", "铁蒺藜" ],
    "StS2 Colorless-CaltropsPlus": [ "Caltrops+", "铁蒺藜+" ],
    "StS2 Colorless-Catastrophe": [ "Catastrophe", "横祸" ],
    "StS2 Colorless-CatastrophePlus": [ "Catastrophe+", "横祸+" ],
    "StS2 Colorless-Clash": [ "Clash", "交锋" ],
    "StS2 Colorless-ClashPlus": [ "Clash+", "交锋+" ],
    "StS2 Colorless-Coordinate": [ "Coordinate", "协同配合" ],
    "StS2 Colorless-CoordinatePlus": [ "Coordinate+", "协同配合+" ],
    "StS2 Colorless-DarkShackles": [ "Dark Shackles", "DarkShackles", "黑暗镣铐" ],
    "StS2 Colorless-DarkShacklesPlus": [ "Dark Shackles+", "DarkShackles+", "黑暗镣铐+" ],
    "StS2 Colorless-Dazed": [ "Dazed", "晕眩" ],
    "StS2 Colorless-Debris": [ "Debris", "碎屑" ],
    "StS2 Colorless-Discovery": [ "Discovery", "发现" ],
    "StS2 Colorless-DiscoveryPlus": [ "Discovery+", "发现+" ],
    "StS2 Colorless-Disintegration": [ "Disintegration", "瓦解" ],
    "StS2 Colorless-Distraction": [ "Distraction", "声东击西" ],
    "StS2 Colorless-DistractionPlus": [ "Distraction+", "声东击西+" ],
    "StS2 Colorless-DramaticEntrance": [ "Dramatic Entrance", "DramaticEntrance", "闪亮登场" ],
    "StS2 Colorless-DramaticEntrancePlus": [ "Dramatic Entrance+", "DramaticEntrance+", "闪亮登场+" ],
    "StS2 Colorless-DualWield": [ "Dual Wield", "DualWield", "双持" ],
    "StS2 Colorless-DualWieldPlus": [ "Dual Wield+", "DualWield+", "双持+" ],
    "StS2 Colorless-Enlightenment": [ "Enlightenment", "开悟" ],
    "StS2 Colorless-EnlightenmentPlus": [ "Enlightenment+", "开悟+" ],
    "StS2 Colorless-Entrench": [ "Entrench", "巩固" ],
    "StS2 Colorless-EntrenchPlus": [ "Entrench+", "巩固+" ],
    "StS2 Colorless-Entropy": [ "Entropy", "熵" ],
    "StS2 Colorless-EntropyPlus": [ "Entropy+", "熵+" ],
    "StS2 Colorless-Equilibrium": [ "Equilibrium", "均衡" ],
    "StS2 Colorless-EquilibriumPlus": [ "Equilibrium+", "均衡+" ],
    "StS2 Colorless-EternalArmor": [ "Eternal Armor", "EternalArmor", "永恒铠甲" ],
    "StS2 Colorless-EternalArmorPlus": [ "Eternal Armor+", "EternalArmor+", "永恒铠甲+" ],
    "StS2 Colorless-Exterminate": [ "Exterminate", "杀灭" ],
    "StS2 Colorless-ExterminatePlus": [ "Exterminate+", "杀灭+" ],
    "StS2 Colorless-Fasten": [ "Fasten", "勒紧" ],
    "StS2 Colorless-FastenPlus": [ "Fasten+", "勒紧+" ],
    "StS2 Colorless-FeedingFrenzy": [ "Feeding Frenzy", "FeedingFrenzy", "疯狂进食" ],
    "StS2 Colorless-FeedingFrenzyPlus": [ "Feeding Frenzy+", "FeedingFrenzy+", "疯狂进食+" ],
    "StS2 Colorless-Finesse": [ "Finesse", "妙计" ],
    "StS2 Colorless-FinessePlus": [ "Finesse+", "妙计+" ],
    "StS2 Colorless-Fisticuffs": [ "Fisticuffs", "拳斗" ],
    "StS2 Colorless-FisticuffsPlus": [ "Fisticuffs+", "拳斗+" ],
    "StS2 Colorless-FlashOfSteel": [ "Flash of Steel", "FlashofSteel", "亮剑" ],
    "StS2 Colorless-FlashOfSteelPlus": [ "Flash of Steel+", "FlashofSteel+", "亮剑+" ],
    "StS2 Colorless-FranticEscape": [ "Frantic Escape", "FranticEscape", "狂乱逃离" ],
    "StS2 Colorless-Fuel": [ "Fuel", "燃料" ],
    "StS2 Colorless-FuelPlus": [ "Fuel+", "燃料+" ],
    "StS2 Colorless-GangUp": [ "Gang Up", "GangUp", "群起攻之" ],
    "StS2 Colorless-GangUpPlus": [ "Gang Up+", "GangUp+", "群起攻之+" ],
    "StS2 Colorless-GiantRock": [ "Giant Rock", "GiantRock", "巨石" ],
    "StS2 Colorless-GiantRockPlus": [ "Giant Rock+", "GiantRock+", "巨石+" ],
    "StS2 Colorless-GoldAxe": [ "Gold Axe", "GoldAxe", "金斧" ],
    "StS2 Colorless-GoldAxePlus": [ "Gold Axe+", "GoldAxe+", "金斧+" ],
    "StS2 Colorless-HandOfGreed": [ "Hand of Greed", "HandofGreed", "贪婪之手" ],
    "StS2 Colorless-HandOfGreedPlus": [ "Hand of Greed+", "HandofGreed+", "贪婪之手+" ],
    "StS2 Colorless-HelloWorld": [ "Hello World", "HelloWorld", "你好世界" ],
    "StS2 Colorless-HelloWorldPlus": [ "Hello World+", "HelloWorld+", "你好世界+" ],
    "StS2 Colorless-HiddenGem": [ "Hidden Gem", "HiddenGem", "未掘宝石" ],
    "StS2 Colorless-HiddenGemPlus": [ "Hidden Gem+", "HiddenGem+", "未掘宝石+" ],
    "StS2 Colorless-HuddleUp": [ "Huddle Up", "HuddleUp", "抱团" ],
    "StS2 Colorless-HuddleUpPlus": [ "Huddle Up+", "HuddleUp+", "抱团+" ],
    "StS2 Colorless-Impatience": [ "Impatience", "急躁" ],
    "StS2 Colorless-ImpatiencePlus": [ "Impatience+", "急躁+" ],
    "StS2 Colorless-Infection": [ "Infection", "感染" ],
    "StS2 Colorless-Intercept": [ "Intercept", "拦截" ],
    "StS2 Colorless-InterceptPlus": [ "Intercept+", "拦截+" ],
    "StS2 Colorless-JackOfAllTrades": [ "Jack of All Trades", "JackofAllTrades", "花样百出" ],
    "StS2 Colorless-JackOfAllTradesPlus": [ "Jack of All Trades+", "JackofAllTrades+", "花样百出+" ],
    "StS2 Colorless-Jackpot": [ "Jackpot", "大奖" ],
    "StS2 Colorless-JackpotPlus": [ "Jackpot+", "大奖+" ],
    "StS2 Colorless-Knockdown": [ "Knockdown", "击倒" ],
    "StS2 Colorless-KnockdownPlus": [ "Knockdown+", "击倒+" ],
    "StS2 Colorless-Lift": [ "Lift", "托举" ],
    "StS2 Colorless-LiftPlus": [ "Lift+", "托举+" ],
    "StS2 Colorless-Luminesce": [ "Luminesce", "冷光" ],
    "StS2 Colorless-LuminescePlus": [ "Luminesce+", "冷光+" ],
    "StS2 Colorless-MadScience": [ "Mad Science", "MadScience", "疯狂科学" ],
    "StS2 Colorless-MadScience-Chaos": [ "Mad Science", "MadScience", "疯狂科学" ],
    "StS2 Colorless-MadScience-ChaosPlus": [ "Mad Science+", "MadScience+", "疯狂科学+" ],
    "StS2 Colorless-MadScience-Choking": [ "Mad Science", "MadScience", "疯狂科学" ],
    "StS2 Colorless-MadScience-ChokingPlus": [ "Mad Science+", "MadScience+", "疯狂科学+" ],
    "StS2 Colorless-MadScience-Curious": [ "Mad Science", "MadScience", "疯狂科学" ],
    "StS2 Colorless-MadScience-CuriousPlus": [ "Mad Science+", "MadScience+", "疯狂科学+" ],
    "StS2 Colorless-MadScience-Energized": [ "Mad Science", "MadScience", "疯狂科学" ],
    "StS2 Colorless-MadScience-EnergizedPlus": [ "Mad Science+", "MadScience+", "疯狂科学+" ],
    "StS2 Colorless-MadScience-Expertise": [ "Mad Science", "MadScience", "疯狂科学" ],
    "StS2 Colorless-MadScience-ExpertisePlus": [ "Mad Science+", "MadScience+", "疯狂科学+" ],
    "StS2 Colorless-MadScience-Improvement": [ "Mad Science", "MadScience", "疯狂科学" ],
    "StS2 Colorless-MadScience-ImprovementPlus": [ "Mad Science+", "MadScience+", "疯狂科学+" ],
    "StS2 Colorless-MadScience-Sapping": [ "Mad Science", "MadScience", "疯狂科学" ],
    "StS2 Colorless-MadScience-SappingPlus": [ "Mad Science+", "MadScience+", "疯狂科学+" ],
    "StS2 Colorless-MadScience-Violence": [ "Mad Science", "MadScience", "疯狂科学" ],
    "StS2 Colorless-MadScience-ViolencePlus": [ "Mad Science+", "MadScience+", "疯狂科学+" ],
    "StS2 Colorless-MadScience-Wisdom": [ "Mad Science", "MadScience", "疯狂科学" ],
    "StS2 Colorless-MadScience-WisdomPlus": [ "Mad Science+", "MadScience+", "疯狂科学+" ],
    "StS2 Colorless-MadSciencePlus": [ "Mad Science+", "MadScience+", "疯狂科学+" ],
    "StS2 Colorless-MasterOfStrategy": [ "Master of Strategy", "MasterofStrategy", "战略大师" ],
    "StS2 Colorless-MasterOfStrategyPlus": [ "Master of Strategy+", "MasterofStrategy+", "战略大师+" ],
    "StS2 Colorless-Maul": [ "Maul", "撕咬" ],
    "StS2 Colorless-MaulPlus": [ "Maul+", "撕咬+" ],
    "StS2 Colorless-Mayhem": [ "Mayhem", "乱战" ],
    "StS2 Colorless-MayhemPlus": [ "Mayhem+", "乱战+" ],
    "StS2 Colorless-Metamorphosis": [ "Metamorphosis", "羽化" ],
    "StS2 Colorless-MetamorphosisPlus": [ "Metamorphosis+", "羽化+" ],
    "StS2 Colorless-Mimic": [ "Mimic", "拟态" ],
    "StS2 Colorless-MimicPlus": [ "Mimic+", "拟态+" ],
    "StS2 Colorless-MindBlast": [ "Mind Blast", "MindBlast", "心灵震慑" ],
    "StS2 Colorless-MindBlastPlus": [ "Mind Blast+", "MindBlast+", "心灵震慑+" ],
    "StS2 Colorless-MindRot": [ "Mind Rot", "MindRot", "心灵腐化" ],
    "StS2 Colorless-MinionDiveBomb": [ "Minion Dive Bomb", "MinionDiveBomb", "仆从俯冲" ],
    "StS2 Colorless-MinionDiveBombPlus": [ "Minion Dive Bomb+", "MinionDiveBomb+", "仆从俯冲+" ],
    "StS2 Colorless-MinionSacrifice": [ "Minion Sacrifice", "MinionSacrifice", "仆从捐躯" ],
    "StS2 Colorless-MinionSacrificePlus": [ "Minion Sacrifice+", "MinionSacrifice+", "仆从捐躯+" ],
    "StS2 Colorless-MinionStrike": [ "Minion Strike", "MinionStrike", "仆从打击" ],
    "StS2 Colorless-MinionStrikePlus": [ "Minion Strike+", "MinionStrike+", "仆从打击+" ],
    "StS2 Colorless-NeowsFury": [ "Neow's Fury", "NeowsFury", "涅奥之怒" ],
    "StS2 Colorless-NeowsFuryPlus": [ "Neow's Fury+", "NeowsFury+", "涅奥之怒+" ],
    "StS2 Colorless-Nostalgia": [ "Nostalgia", "怀旧" ],
    "StS2 Colorless-NostalgiaPlus": [ "Nostalgia+", "怀旧+" ],
    "StS2 Colorless-Omnislice": [ "Omnislice", "万向斩" ],
    "StS2 Colorless-OmnislicePlus": [ "Omnislice+", "万向斩+" ],
    "StS2 Colorless-Outmaneuver": [ "Outmaneuver", "抢占先机" ],
    "StS2 Colorless-OutmaneuverPlus": [ "Outmaneuver+", "抢占先机+" ],
    "StS2 Colorless-Panache": [ "Panache", "神气制胜" ],
    "StS2 Colorless-PanachePlus": [ "Panache+", "神气制胜+" ],
    "StS2 Colorless-PanicButton": [ "Panic Button", "PanicButton", "应急按钮" ],
    "StS2 Colorless-PanicButtonPlus": [ "Panic Button+", "PanicButton+", "应急按钮+" ],
    "StS2 Colorless-Peck": [ "Peck", "啄击" ],
    "StS2 Colorless-PeckPlus": [ "Peck+", "啄击+" ],
    "StS2 Colorless-PrepTime": [ "Prep Time", "PrepTime", "准备时间" ],
    "StS2 Colorless-PrepTimePlus": [ "Prep Time+", "PrepTime+", "准备时间+" ],
    "StS2 Colorless-Production": [ "Production", "生产制造" ],
    "StS2 Colorless-ProductionPlus": [ "Production+", "生产制造+" ],
    "StS2 Colorless-Prolong": [ "Prolong", "延伸" ],
    "StS2 Colorless-ProlongPlus": [ "Prolong+", "延伸+" ],
    "StS2 Colorless-Prowess": [ "Prowess", "非凡技艺" ],
    "StS2 Colorless-ProwessPlus": [ "Prowess+", "非凡技艺+" ],
    "StS2 Colorless-Purity": [ "Purity", "净化" ],
    "StS2 Colorless-PurityPlus": [ "Purity+", "净化+" ],
    "StS2 Colorless-Rally": [ "Rally", "集结" ],
    "StS2 Colorless-RallyPlus": [ "Rally+", "集结+" ],
    "StS2 Colorless-Rebound": [ "Rebound", "弹回" ],
    "StS2 Colorless-ReboundPlus": [ "Rebound+", "弹回+" ],
    "StS2 Colorless-Relax": [ "Relax", "放松" ],
    "StS2 Colorless-RelaxPlus": [ "Relax+", "放松+" ],
    "StS2 Colorless-Rend": [ "Rend", "撕碎" ],
    "StS2 Colorless-RendPlus": [ "Rend+", "撕碎+" ],
    "StS2 Colorless-Restlessness": [ "Restlessness", "心神不宁" ],
    "StS2 Colorless-RestlessnessPlus": [ "Restlessness+", "心神不宁+" ],
    "StS2 Colorless-RipAndTear": [ "Rip and Tear", "RipandTear", "狂乱撕扯" ],
    "StS2 Colorless-RipAndTearPlus": [ "Rip and Tear+", "RipandTear+", "狂乱撕扯+" ],
    "StS2 Colorless-RollingBoulder": [ "Rolling Boulder", "RollingBoulder", "滚石" ],
    "StS2 Colorless-RollingBoulderPlus": [ "Rolling Boulder+", "RollingBoulder+", "滚石+" ],
    "StS2 Colorless-Salvo": [ "Salvo", "箭雨" ],
    "StS2 Colorless-SalvoPlus": [ "Salvo+", "箭雨+" ],
    "StS2 Colorless-Scrawl": [ "Scrawl", "潦草急就" ],
    "StS2 Colorless-ScrawlPlus": [ "Scrawl+", "潦草急就+" ],
    "StS2 Colorless-SecretTechnique": [ "Secret Technique", "SecretTechnique", "秘密技法" ],
    "StS2 Colorless-SecretTechniquePlus": [ "Secret Technique+", "SecretTechnique+", "秘密技法+" ],
    "StS2 Colorless-SecretWeapon": [ "Secret Weapon", "SecretWeapon", "秘密武器" ],
    "StS2 Colorless-SecretWeaponPlus": [ "Secret Weapon+", "SecretWeapon+", "秘密武器+" ],
    "StS2 Colorless-SeekerStrike": [ "Seeker Strike", "SeekerStrike", "探寻打击" ],
    "StS2 Colorless-SeekerStrikePlus": [ "Seeker Strike+", "SeekerStrike+", "探寻打击+" ],
    "StS2 Colorless-Shiv": [ "Shiv", "小刀" ],
    "StS2 Colorless-ShivPlus": [ "Shiv+", "小刀+" ],
    "StS2 Colorless-Shockwave": [ "Shockwave", "震荡波" ],
    "StS2 Colorless-ShockwavePlus": [ "Shockwave+", "震荡波+" ],
    "StS2 Colorless-Slimed": [ "Slimed", "黏液" ],
    "StS2 Colorless-Sloth": [ "Sloth", "懒惰" ],
    "StS2 Colorless-Soot": [ "Soot", "煤灰" ],
    "StS2 Colorless-Soul": [ "Soul", "灵魂" ],
    "StS2 Colorless-SoulPlus": [ "Soul+", "灵魂+" ],
    "StS2 Colorless-SovereignBlade": [ "Sovereign Blade", "SovereignBlade", "君王之剑" ],
    "StS2 Colorless-SovereignBladePlus": [ "Sovereign Blade+", "SovereignBlade+", "君王之剑+" ],
    "StS2 Colorless-Splash": [ "Splash", "飞溅" ],
    "StS2 Colorless-SplashPlus": [ "Splash+", "飞溅+" ],
    "StS2 Colorless-Squash": [ "Squash", "压扁" ],
    "StS2 Colorless-SquashPlus": [ "Squash+", "压扁+" ],
    "StS2 Colorless-Stack": [ "Stack", "堆栈" ],
    "StS2 Colorless-StackPlus": [ "Stack+", "堆栈+" ],
    "StS2 Colorless-Stratagem": [ "Stratagem", "计策" ],
    "StS2 Colorless-StratagemPlus": [ "Stratagem+", "计策+" ],
    "StS2 Colorless-SweepingGaze": [ "Sweeping Gaze", "SweepingGaze", "扫荡凝视" ],
    "StS2 Colorless-SweepingGazePlus": [ "Sweeping Gaze+", "SweepingGaze+", "扫荡凝视+" ],
    "StS2 Colorless-TagTeam": [ "Tag Team", "TagTeam", "双打组合" ],
    "StS2 Colorless-TagTeamPlus": [ "Tag Team+", "TagTeam+", "双打组合+" ],
    "StS2 Colorless-TheBomb": [ "The Bomb", "TheBomb", "炸弹" ],
    "StS2 Colorless-TheBombPlus": [ "The Bomb+", "TheBomb+", "炸弹+" ],
    "StS2 Colorless-TheGambit": [ "The Gambit", "TheGambit", "孤注一掷" ],
    "StS2 Colorless-TheGambitPlus": [ "The Gambit+", "TheGambit+", "孤注一掷+" ],
    "StS2 Colorless-ThinkingAhead": [ "Thinking Ahead", "ThinkingAhead", "深谋远虑" ],
    "StS2 Colorless-ThinkingAheadPlus": [ "Thinking Ahead+", "ThinkingAhead+", "深谋远虑+" ],
    "StS2 Colorless-ThrummingHatchet": [ "Thrumming Hatchet", "ThrummingHatchet", "无休手斧" ],
    "StS2 Colorless-ThrummingHatchetPlus": [ "Thrumming Hatchet+", "ThrummingHatchet+", "无休手斧+" ],
    "StS2 Colorless-ToricToughness": [ "Toric Toughness", "ToricToughness", "坚韧之环" ],
    "StS2 Colorless-ToricToughnessPlus": [ "Toric Toughness+", "ToricToughness+", "坚韧之环+" ],
    "StS2 Colorless-Toxic": [ "Toxic", "毒素" ],
    "StS2 Colorless-UltimateDefend": [ "Ultimate Defend", "UltimateDefend", "究极防御" ],
    "StS2 Colorless-UltimateDefendPlus": [ "Ultimate Defend+", "UltimateDefend+", "究极防御+" ],
    "StS2 Colorless-UltimateStrike": [ "Ultimate Strike", "UltimateStrike", "究极打击" ],
    "StS2 Colorless-UltimateStrikePlus": [ "Ultimate Strike+", "UltimateStrike+", "究极打击+" ],
    "StS2 Colorless-Void": [ "Void", "虚空" ],
    "StS2 Colorless-Volley": [ "Volley", "连射" ],
    "StS2 Colorless-VolleyPlus": [ "Volley+", "连射+" ],
    "StS2 Colorless-WasteAway": [ "Waste Away", "WasteAway", "衰朽" ],
    "StS2 Colorless-Whistle": [ "Whistle", "吹哨" ],
    "StS2 Colorless-WhistlePlus": [ "Whistle+", "吹哨+" ],
    "StS2 Colorless-Wish": [ "Wish", "许愿" ],
    "StS2 Colorless-WishPlus": [ "Wish+", "许愿+" ],
    "StS2 Colorless-Wither": [ "Wither", "凋萎" ],
    "StS2 Colorless-Wound": [ "Wound", "伤口" ],
    "StS2 Curse-AscendersBane": [ "Ascender's Bane", "AscendersBane", "进阶之灾" ],
    "StS2 Curse-BadLuck": [ "Bad Luck", "BadLuck", "霉运" ],
    "StS2 Curse-Clumsy": [ "Clumsy", "笨拙" ],
    "StS2 Curse-CurseOfTheBell": [ "Curse of the Bell", "CurseoftheBell", "铃铛的诅咒" ],
    "StS2 Curse-Debt": [ "Debt", "债务" ],
    "StS2 Curse-Decay": [ "Decay", "腐朽" ],
    "StS2 Curse-Doubt": [ "Doubt", "疑虑" ],
    "StS2 Curse-Enthralled": [ "Enthralled", "执迷" ],
    "StS2 Curse-Folly": [ "Folly", "愚行" ],
    "StS2 Curse-Greed": [ "Greed", "贪婪" ],
    "StS2 Curse-Guilty": [ "Guilty", "愧疚" ],
    "StS2 Curse-Injury": [ "Injury", "受伤" ],
    "StS2 Curse-Normality": [ "Normality", "凡庸" ],
    "StS2 Curse-PoorSleep": [ "Poor Sleep", "PoorSleep", "睡眠不佳" ],
    "StS2 Curse-Regret": [ "Regret", "悔恨" ],
    "StS2 Curse-Shame": [ "Shame", "羞耻" ],
    "StS2 Curse-SporeMind": [ "Spore Mind", "SporeMind", "孢子心灵" ],
    "StS2 Curse-Writhe": [ "Writhe", "苦恼" ],
    "StS2 Defect-AdaptiveStrike": [ "Adaptive Strike", "AdaptiveStrike", "适应打击" ],
    "StS2 Defect-AdaptiveStrikePlus": [ "Adaptive Strike+", "AdaptiveStrike+", "适应打击+" ],
    "StS2 Defect-AllForOne": [ "All for One", "AllforOne", "万物一心" ],
    "StS2 Defect-AllForOnePlus": [ "All for One+", "AllforOne+", "万物一心+" ],
    "StS2 Defect-BallLightning": [ "Ball Lightning", "BallLightning", "球状闪电" ],
    "StS2 Defect-BallLightningPlus": [ "Ball Lightning+", "BallLightning+", "球状闪电+" ],
    "StS2 Defect-Barrage": [ "Barrage", "弹幕齐射" ],
    "StS2 Defect-BarragePlus": [ "Barrage+", "弹幕齐射+" ],
    "StS2 Defect-BeamCell": [ "Beam Cell", "BeamCell", "光束射线" ],
    "StS2 Defect-BeamCellPlus": [ "Beam Cell+", "BeamCell+", "光束射线+" ],
    "StS2 Defect-BiasedCognition": [ "Biased Cognition", "BiasedCognition", "偏差认知" ],
    "StS2 Defect-BiasedCognitionPlus": [ "Biased Cognition+", "BiasedCognition+", "偏差认知+" ],
    "StS2 Defect-BoostAway": [ "Boost Away", "BoostAway", "高速脱离" ],
    "StS2 Defect-BoostAwayPlus": [ "Boost Away+", "BoostAway+", "高速脱离+" ],
    "StS2 Defect-BootSequence": [ "Boot Sequence", "BootSequence", "启动流程" ],
    "StS2 Defect-BootSequencePlus": [ "Boot Sequence+", "BootSequence+", "启动流程+" ],
    "StS2 Defect-Buffer": [ "Buffer", "缓冲" ],
    "StS2 Defect-BufferPlus": [ "Buffer+", "缓冲+" ],
    "StS2 Defect-BulkUp": [ "Bulk Up", "BulkUp", "暴涨" ],
    "StS2 Defect-BulkUpPlus": [ "Bulk Up+", "BulkUp+", "暴涨+" ],
    "StS2 Defect-Capacitor": [ "Capacitor", "扩容" ],
    "StS2 Defect-CapacitorPlus": [ "Capacitor+", "扩容+" ],
    "StS2 Defect-Chaos": [ "Chaos", "混沌" ],
    "StS2 Defect-ChaosPlus": [ "Chaos+", "混沌+" ],
    "StS2 Defect-ChargeBattery": [ "Charge Battery", "ChargeBattery", "充电" ],
    "StS2 Defect-ChargeBatteryPlus": [ "Charge Battery+", "ChargeBattery+", "充电+" ],
    "StS2 Defect-Chill": [ "Chill", "冰寒" ],
    "StS2 Defect-ChillPlus": [ "Chill+", "冰寒+" ],
    "StS2 Defect-Claw": [ "Claw", "爪击" ],
    "StS2 Defect-ClawPlus": [ "Claw+", "爪击+" ],
    "StS2 Defect-ColdSnap": [ "Cold Snap", "ColdSnap", "寒流" ],
    "StS2 Defect-ColdSnapPlus": [ "Cold Snap+", "ColdSnap+", "寒流+" ],
    "StS2 Defect-Compact": [ "Compact", "压缩" ],
    "StS2 Defect-CompactPlus": [ "Compact+", "压缩+" ],
    "StS2 Defect-CompileDriver": [ "Compile Driver", "CompileDriver", "编译冲击" ],
    "StS2 Defect-CompileDriverPlus": [ "Compile Driver+", "CompileDriver+", "编译冲击+" ],
    "StS2 Defect-ConsumingShadow": [ "Consuming Shadow", "ConsumingShadow", "吞噬暗影" ],
    "StS2 Defect-ConsumingShadowPlus": [ "Consuming Shadow+", "ConsumingShadow+", "吞噬暗影+" ],
    "StS2 Defect-Coolant": [ "Coolant", "冷却剂" ],
    "StS2 Defect-CoolantPlus": [ "Coolant+", "冷却剂+" ],
    "StS2 Defect-Coolheaded": [ "Coolheaded", "冷静头脑" ],
    "StS2 Defect-CoolheadedPlus": [ "Coolheaded+", "冷静头脑+" ],
    "StS2 Defect-CreativeAI": [ "Creative AI", "CreativeAI", "创造性AI" ],
    "StS2 Defect-CreativeAIPlus": [ "Creative AI+", "CreativeAI+", "创造性AI+" ],
    "StS2 Defect-Darkness": [ "Darkness", "漆黑" ],
    "StS2 Defect-DarknessPlus": [ "Darkness+", "漆黑+" ],
    "StS2 Defect-Defend": [ "Defend", "防御" ],
    "StS2 Defect-DefendPlus": [ "Defend+", "防御+" ],
    "StS2 Defect-Defragment": [ "Defragment", "碎片整理" ],
    "StS2 Defect-DefragmentPlus": [ "Defragment+", "碎片整理+" ],
    "StS2 Defect-DoubleEnergy": [ "Double Energy", "DoubleEnergy", "双倍能量" ],
    "StS2 Defect-DoubleEnergyPlus": [ "Double Energy+", "DoubleEnergy+", "双倍能量+" ],
    "StS2 Defect-Dualcast": [ "Dualcast", "双重释放" ],
    "StS2 Defect-DualcastPlus": [ "Dualcast+", "双重释放+" ],
    "StS2 Defect-EchoForm": [ "Echo Form", "EchoForm", "回响形态" ],
    "StS2 Defect-EchoFormPlus": [ "Echo Form+", "EchoForm+", "回响形态+" ],
    "StS2 Defect-EnergySurge": [ "Energy Surge", "EnergySurge", "能量涌动" ],
    "StS2 Defect-EnergySurgePlus": [ "Energy Surge+", "EnergySurge+", "能量涌动+" ],
    "StS2 Defect-Feral": [ "Feral", "野性" ],
    "StS2 Defect-FeralPlus": [ "Feral+", "野性+" ],
    "StS2 Defect-FightThrough": [ "Fight Through", "FightThrough", "强撑" ],
    "StS2 Defect-FightThroughPlus": [ "Fight Through+", "FightThrough+", "强撑+" ],
    "StS2 Defect-FlakCannon": [ "Flak Cannon", "FlakCannon", "散射炮" ],
    "StS2 Defect-FlakCannonPlus": [ "Flak Cannon+", "FlakCannon+", "散射炮+" ],
    "StS2 Defect-FocusedStrike": [ "Focused Strike", "FocusedStrike", "集中打击" ],
    "StS2 Defect-FocusedStrikePlus": [ "Focused Strike+", "FocusedStrike+", "集中打击+" ],
    "StS2 Defect-FTL": [ "FTL", "超越光速" ],
    "StS2 Defect-FTLPlus": [ "FTL+", "超越光速+" ],
    "StS2 Defect-Fusion": [ "Fusion", "聚变" ],
    "StS2 Defect-FusionPlus": [ "Fusion+", "聚变+" ],
    "StS2 Defect-GeneticAlgorithm": [ "Genetic Algorithm", "GeneticAlgorithm", "遗传算法" ],
    "StS2 Defect-GeneticAlgorithmPlus": [ "Genetic Algorithm+", "GeneticAlgorithm+", "遗传算法+" ],
    "StS2 Defect-Glacier": [ "Glacier", "冰川" ],
    "StS2 Defect-GlacierPlus": [ "Glacier+", "冰川+" ],
    "StS2 Defect-Glasswork": [ "Glasswork", "玻璃工艺" ],
    "StS2 Defect-GlassworkPlus": [ "Glasswork+", "玻璃工艺+" ],
    "StS2 Defect-GoForTheEyes": [ "Go for the Eyes", "GofortheEyes", "眼部攻击" ],
    "StS2 Defect-GoForTheEyesPlus": [ "Go for the Eyes+", "GofortheEyes+", "眼部攻击+" ],
    "StS2 Defect-GunkUp": [ "Gunk Up", "GunkUp", "污秽攻击" ],
    "StS2 Defect-GunkUpPlus": [ "Gunk Up+", "GunkUp+", "污秽攻击+" ],
    "StS2 Defect-Hailstorm": [ "Hailstorm", "冰雹风暴" ],
    "StS2 Defect-HailstormPlus": [ "Hailstorm+", "冰雹风暴+" ],
    "StS2 Defect-HelixDrill": [ "Helix Drill", "HelixDrill", "螺旋钻击" ],
    "StS2 Defect-HelixDrillPlus": [ "Helix Drill+", "HelixDrill+", "螺旋钻击+" ],
    "StS2 Defect-Hologram": [ "Hologram", "全息影像" ],
    "StS2 Defect-HologramPlus": [ "Hologram+", "全息影像+" ],
    "StS2 Defect-Hotfix": [ "Hotfix", "热修复" ],
    "StS2 Defect-HotfixPlus": [ "Hotfix+", "热修复+" ],
    "StS2 Defect-Hyperbeam": [ "Hyperbeam", "超能光束" ],
    "StS2 Defect-HyperbeamPlus": [ "Hyperbeam+", "超能光束+" ],
    "StS2 Defect-IceLance": [ "Ice Lance", "IceLance", "冰之长枪" ],
    "StS2 Defect-IceLancePlus": [ "Ice Lance+", "IceLance+", "冰之长枪+" ],
    "StS2 Defect-Ignition": [ "Ignition", "引火" ],
    "StS2 Defect-IgnitionPlus": [ "Ignition+", "引火+" ],
    "StS2 Defect-Iteration": [ "Iteration", "迭代" ],
    "StS2 Defect-IterationPlus": [ "Iteration+", "迭代+" ],
    "StS2 Defect-Leap": [ "Leap", "飞跃" ],
    "StS2 Defect-LeapPlus": [ "Leap+", "飞跃+" ],
    "StS2 Defect-LightningRod": [ "Lightning Rod", "LightningRod", "引雷针" ],
    "StS2 Defect-LightningRodPlus": [ "Lightning Rod+", "LightningRod+", "引雷针+" ],
    "StS2 Defect-Loop": [ "Loop", "循环" ],
    "StS2 Defect-LoopPlus": [ "Loop+", "循环+" ],
    "StS2 Defect-MachineLearning": [ "Machine Learning", "MachineLearning", "机器学习" ],
    "StS2 Defect-MachineLearningPlus": [ "Machine Learning+", "MachineLearning+", "机器学习+" ],
    "StS2 Defect-MeteorStrike": [ "Meteor Strike", "MeteorStrike", "陨石打击" ],
    "StS2 Defect-MeteorStrikePlus": [ "Meteor Strike+", "MeteorStrike+", "陨石打击+" ],
    "StS2 Defect-Modded": [ "Modded", "模组改造" ],
    "StS2 Defect-ModdedPlus": [ "Modded+", "模组改造+" ],
    "StS2 Defect-MomentumStrike": [ "Momentum Strike", "MomentumStrike", "趁势打击" ],
    "StS2 Defect-MomentumStrikePlus": [ "Momentum Strike+", "MomentumStrike+", "趁势打击+" ],
    "StS2 Defect-MultiCast": [ "Multi-Cast", "MultiCast", "多重释放" ],
    "StS2 Defect-MultiCastPlus": [ "Multi-Cast+", "MultiCast+", "多重释放+" ],
    "StS2 Defect-Null": [ "Null", "空值" ],
    "StS2 Defect-NullPlus": [ "Null+", "空值+" ],
    "StS2 Defect-Overclock": [ "Overclock", "超频" ],
    "StS2 Defect-OverclockPlus": [ "Overclock+", "超频+" ],
    "StS2 Defect-Quadcast": [ "Quadcast", "四重释放" ],
    "StS2 Defect-QuadcastPlus": [ "Quadcast+", "四重释放+" ],
    "StS2 Defect-Rainbow": [ "Rainbow", "彩虹" ],
    "StS2 Defect-RainbowPlus": [ "Rainbow+", "彩虹+" ],
    "StS2 Defect-Reboot": [ "Reboot", "重启" ],
    "StS2 Defect-RebootPlus": [ "Reboot+", "重启+" ],
    "StS2 Defect-Refract": [ "Refract", "折射" ],
    "StS2 Defect-RefractPlus": [ "Refract+", "折射+" ],
    "StS2 Defect-RocketPunch": [ "Rocket Punch", "RocketPunch", "火箭飞拳" ],
    "StS2 Defect-RocketPunchPlus": [ "Rocket Punch+", "RocketPunch+", "火箭飞拳+" ],
    "StS2 Defect-Scavenge": [ "Scavenge", "内存清理" ],
    "StS2 Defect-ScavengePlus": [ "Scavenge+", "内存清理+" ],
    "StS2 Defect-Scrape": [ "Scrape", "刮削" ],
    "StS2 Defect-ScrapePlus": [ "Scrape+", "刮削+" ],
    "StS2 Defect-ShadowShield": [ "Shadow Shield", "ShadowShield", "暗影之盾" ],
    "StS2 Defect-ShadowShieldPlus": [ "Shadow Shield+", "ShadowShield+", "暗影之盾+" ],
    "StS2 Defect-Shatter": [ "Shatter", "打碎" ],
    "StS2 Defect-ShatterPlus": [ "Shatter+", "打碎+" ],
    "StS2 Defect-SignalBoost": [ "Signal Boost", "SignalBoost", "信号增强" ],
    "StS2 Defect-SignalBoostPlus": [ "Signal Boost+", "SignalBoost+", "信号增强+" ],
    "StS2 Defect-Skim": [ "Skim", "快速检索" ],
    "StS2 Defect-SkimPlus": [ "Skim+", "快速检索+" ],
    "StS2 Defect-Smokestack": [ "Smokestack", "烟囱" ],
    "StS2 Defect-SmokestackPlus": [ "Smokestack+", "烟囱+" ],
    "StS2 Defect-Spinner": [ "Spinner", "旋转工艺" ],
    "StS2 Defect-SpinnerPlus": [ "Spinner+", "旋转工艺+" ],
    "StS2 Defect-Storm": [ "Storm", "雷暴" ],
    "StS2 Defect-StormPlus": [ "Storm+", "雷暴+" ],
    "StS2 Defect-Strike": [ "Strike", "打击" ],
    "StS2 Defect-StrikePlus": [ "Strike+", "打击+" ],
    "StS2 Defect-Subroutine": [ "Subroutine", "子程序" ],
    "StS2 Defect-SubroutinePlus": [ "Subroutine+", "子程序+" ],
    "StS2 Defect-Sunder": [ "Sunder", "分离" ],
    "StS2 Defect-SunderPlus": [ "Sunder+", "分离+" ],
    "StS2 Defect-Supercritical": [ "Supercritical", "超临界态" ],
    "StS2 Defect-SupercriticalPlus": [ "Supercritical+", "超临界态+" ],
    "StS2 Defect-SweepingBeam": [ "Sweeping Beam", "SweepingBeam", "扫荡射线" ],
    "StS2 Defect-SweepingBeamPlus": [ "Sweeping Beam+", "SweepingBeam+", "扫荡射线+" ],
    "StS2 Defect-Synchronize": [ "Synchronize", "同步" ],
    "StS2 Defect-SynchronizePlus": [ "Synchronize+", "同步+" ],
    "StS2 Defect-Synthesis": [ "Synthesis", "人工合成" ],
    "StS2 Defect-SynthesisPlus": [ "Synthesis+", "人工合成+" ],
    "StS2 Defect-Tempest": [ "Tempest", "暴风雨" ],
    "StS2 Defect-TempestPlus": [ "Tempest+", "暴风雨+" ],
    "StS2 Defect-TeslaCoil": [ "Tesla Coil", "TeslaCoil", "特斯拉线圈" ],
    "StS2 Defect-TeslaCoilPlus": [ "Tesla Coil+", "TeslaCoil+", "特斯拉线圈+" ],
    "StS2 Defect-Thunder": [ "Thunder", "雷霆" ],
    "StS2 Defect-ThunderPlus": [ "Thunder+", "雷霆+" ],
    "StS2 Defect-TrashToTreasure": [ "Trash to Treasure", "TrashtoTreasure", "化废为宝" ],
    "StS2 Defect-TrashToTreasurePlus": [ "Trash to Treasure+", "TrashtoTreasure+", "化废为宝+" ],
    "StS2 Defect-TURBO": [ "TURBO", "内核加速" ],
    "StS2 Defect-TURBOPlus": [ "TURBO+", "内核加速+" ],
    "StS2 Defect-Uproar": [ "Uproar", "骚动" ],
    "StS2 Defect-UproarPlus": [ "Uproar+", "骚动+" ],
    "StS2 Defect-Voltaic": [ "Voltaic", "电流相生" ],
    "StS2 Defect-VoltaicPlus": [ "Voltaic+", "电流相生+" ],
    "StS2 Defect-WhiteNoise": [ "White Noise", "WhiteNoise", "白噪声" ],
    "StS2 Defect-WhiteNoisePlus": [ "White Noise+", "WhiteNoise+", "白噪声+" ],
    "StS2 Defect-Zap": [ "Zap", "电击" ],
    "StS2 Defect-ZapPlus": [ "Zap+", "电击+" ],
    "StS2 Ironclad-Aggression": [ "Aggression", "好勇斗狠" ],
    "StS2 Ironclad-AggressionPlus": [ "Aggression+", "好勇斗狠+" ],
    "StS2 Ironclad-Anger": [ "Anger", "愤怒" ],
    "StS2 Ironclad-AngerPlus": [ "Anger+", "愤怒+" ],
    "StS2 Ironclad-Armaments": [ "Armaments", "武装" ],
    "StS2 Ironclad-ArmamentsPlus": [ "Armaments+", "武装+" ],
    "StS2 Ironclad-AshenStrike": [ "Ashen Strike", "AshenStrike", "灰烬打击" ],
    "StS2 Ironclad-AshenStrikePlus": [ "Ashen Strike+", "AshenStrike+", "灰烬打击+" ],
    "StS2 Ironclad-Barricade": [ "Barricade", "壁垒" ],
    "StS2 Ironclad-BarricadePlus": [ "Barricade+", "壁垒+" ],
    "StS2 Ironclad-Bash": [ "Bash", "痛击" ],
    "StS2 Ironclad-BashPlus": [ "Bash+", "痛击+" ],
    "StS2 Ironclad-BattleTrance": [ "Battle Trance", "BattleTrance", "战斗专注" ],
    "StS2 Ironclad-BattleTrancePlus": [ "Battle Trance+", "BattleTrance+", "战斗专注+" ],
    "StS2 Ironclad-Bloodletting": [ "Bloodletting", "放血" ],
    "StS2 Ironclad-BloodlettingPlus": [ "Bloodletting+", "放血+" ],
    "StS2 Ironclad-BloodWall": [ "Blood Wall", "BloodWall", "血墙" ],
    "StS2 Ironclad-BloodWallPlus": [ "Blood Wall+", "BloodWall+", "血墙+" ],
    "StS2 Ironclad-Bludgeon": [ "Bludgeon", "重锤" ],
    "StS2 Ironclad-BludgeonPlus": [ "Bludgeon+", "重锤+" ],
    "StS2 Ironclad-BodySlam": [ "Body Slam", "BodySlam", "全身撞击" ],
    "StS2 Ironclad-BodySlamPlus": [ "Body Slam+", "BodySlam+", "全身撞击+" ],
    "StS2 Ironclad-Brand": [ "Brand", "烙印" ],
    "StS2 Ironclad-BrandPlus": [ "Brand+", "烙印+" ],
    "StS2 Ironclad-Break": [ "Break", "破击" ],
    "StS2 Ironclad-BreakPlus": [ "Break+", "破击+" ],
    "StS2 Ironclad-Breakthrough": [ "Breakthrough", "突破" ],
    "StS2 Ironclad-BreakthroughPlus": [ "Breakthrough+", "突破+" ],
    "StS2 Ironclad-Bully": [ "Bully", "欺凌" ],
    "StS2 Ironclad-BullyPlus": [ "Bully+", "欺凌+" ],
    "StS2 Ironclad-BurningPact": [ "Burning Pact", "BurningPact", "燃烧契约" ],
    "StS2 Ironclad-BurningPactPlus": [ "Burning Pact+", "BurningPact+", "燃烧契约+" ],
    "StS2 Ironclad-Cascade": [ "Cascade", "倾泻" ],
    "StS2 Ironclad-CascadePlus": [ "Cascade+", "倾泻+" ],
    "StS2 Ironclad-Cinder": [ "Cinder", "余烬" ],
    "StS2 Ironclad-CinderPlus": [ "Cinder+", "余烬+" ],
    "StS2 Ironclad-Colossus": [ "Colossus", "巨像" ],
    "StS2 Ironclad-ColossusPlus": [ "Colossus+", "巨像+" ],
    "StS2 Ironclad-Conflagration": [ "Conflagration", "焚烧" ],
    "StS2 Ironclad-ConflagrationPlus": [ "Conflagration+", "焚烧+" ],
    "StS2 Ironclad-Corruption": [ "Corruption", "腐化" ],
    "StS2 Ironclad-CorruptionPlus": [ "Corruption+", "腐化+" ],
    "StS2 Ironclad-CrimsonMantle": [ "Crimson Mantle", "CrimsonMantle", "绯红披风" ],
    "StS2 Ironclad-CrimsonMantlePlus": [ "Crimson Mantle+", "CrimsonMantle+", "绯红披风+" ],
    "StS2 Ironclad-Cruelty": [ "Cruelty", "残酷" ],
    "StS2 Ironclad-CrueltyPlus": [ "Cruelty+", "残酷+" ],
    "StS2 Ironclad-DarkEmbrace": [ "Dark Embrace", "DarkEmbrace", "黑暗之拥" ],
    "StS2 Ironclad-DarkEmbracePlus": [ "Dark Embrace+", "DarkEmbrace+", "黑暗之拥+" ],
    "StS2 Ironclad-Defend": [ "Defend", "防御" ],
    "StS2 Ironclad-DefendPlus": [ "Defend+", "防御+" ],
    "StS2 Ironclad-DemonForm": [ "Demon Form", "DemonForm", "恶魔形态" ],
    "StS2 Ironclad-DemonFormPlus": [ "Demon Form+", "DemonForm+", "恶魔形态+" ],
    "StS2 Ironclad-DemonicShield": [ "Demonic Shield", "DemonicShield", "恶魔护盾" ],
    "StS2 Ironclad-DemonicShieldPlus": [ "Demonic Shield+", "DemonicShield+", "恶魔护盾+" ],
    "StS2 Ironclad-Dismantle": [ "Dismantle", "拆卸" ],
    "StS2 Ironclad-DismantlePlus": [ "Dismantle+", "拆卸+" ],
    "StS2 Ironclad-Dominate": [ "Dominate", "主宰" ],
    "StS2 Ironclad-DominatePlus": [ "Dominate+", "主宰+" ],
    "StS2 Ironclad-DrumOfBattle": [ "Drum of Battle", "DrumofBattle", "战鼓" ],
    "StS2 Ironclad-DrumOfBattle__case-variant": [ "Drum of Battle", "DrumofBattle", "战鼓" ],
    "StS2 Ironclad-DrumOfBattlePlus": [ "Drum of Battle+", "DrumofBattle+", "战鼓+" ],
    "StS2 Ironclad-EvilEye": [ "Evil Eye", "EvilEye", "邪眼" ],
    "StS2 Ironclad-EvilEyePlus": [ "Evil Eye+", "EvilEye+", "邪眼+" ],
    "StS2 Ironclad-ExpectAFight": [ "Expect a Fight", "ExpectaFight", "跃跃欲试" ],
    "StS2 Ironclad-ExpectAFightPlus": [ "Expect a Fight+", "ExpectaFight+", "跃跃欲试+" ],
    "StS2 Ironclad-Feed": [ "Feed", "狂宴" ],
    "StS2 Ironclad-FeedPlus": [ "Feed+", "狂宴+" ],
    "StS2 Ironclad-FeelNoPain": [ "Feel No Pain", "FeelNoPain", "无惧疼痛" ],
    "StS2 Ironclad-FeelNoPainPlus": [ "Feel No Pain+", "FeelNoPain+", "无惧疼痛+" ],
    "StS2 Ironclad-FiendFire": [ "Fiend Fire", "FiendFire", "恶魔之焰" ],
    "StS2 Ironclad-FiendFirePlus": [ "Fiend Fire+", "FiendFire+", "恶魔之焰+" ],
    "StS2 Ironclad-FightMe": [ "Fight Me!", "FightMe!", "与我一战！" ],
    "StS2 Ironclad-FightMePlus": [ "Fight Me!+", "FightMe!+", "与我一战！+" ],
    "StS2 Ironclad-FlameBarrier": [ "Flame Barrier", "FlameBarrier", "火焰屏障" ],
    "StS2 Ironclad-FlameBarrierPlus": [ "Flame Barrier+", "FlameBarrier+", "火焰屏障+" ],
    "StS2 Ironclad-ForgottenRitual": [ "Forgotten Ritual", "ForgottenRitual", "被遗忘的仪式" ],
    "StS2 Ironclad-ForgottenRitualPlus": [ "Forgotten Ritual+", "ForgottenRitual+", "被遗忘的仪式+" ],
    "StS2 Ironclad-Grapple": [ "Grapple", "擒拿" ],
    "StS2 Ironclad-GrapplePlus": [ "Grapple+", "擒拿+" ],
    "StS2 Ironclad-Havoc": [ "Havoc", "破灭" ],
    "StS2 Ironclad-HavocPlus": [ "Havoc+", "破灭+" ],
    "StS2 Ironclad-Headbutt": [ "Headbutt", "头槌" ],
    "StS2 Ironclad-HeadbuttPlus": [ "Headbutt+", "头槌+" ],
    "StS2 Ironclad-Hellraiser": [ "Hellraiser", "地狱狂徒" ],
    "StS2 Ironclad-HellraiserPlus": [ "Hellraiser+", "地狱狂徒+" ],
    "StS2 Ironclad-Hemokinesis": [ "Hemokinesis", "御血术" ],
    "StS2 Ironclad-HemokinesisPlus": [ "Hemokinesis+", "御血术+" ],
    "StS2 Ironclad-HowlFromBeyond": [ "Howl from Beyond", "HowlfromBeyond", "彼岸咆哮" ],
    "StS2 Ironclad-HowlFromBeyondPlus": [ "Howl from Beyond+", "HowlfromBeyond+", "彼岸咆哮+" ],
    "StS2 Ironclad-Impervious": [ "Impervious", "岿然不动" ],
    "StS2 Ironclad-ImperviousPlus": [ "Impervious+", "岿然不动+" ],
    "StS2 Ironclad-InfernalBlade": [ "Infernal Blade", "InfernalBlade", "地狱之刃" ],
    "StS2 Ironclad-InfernalBladePlus": [ "Infernal Blade+", "InfernalBlade+", "地狱之刃+" ],
    "StS2 Ironclad-Inferno": [ "Inferno", "狱火" ],
    "StS2 Ironclad-InfernoPlus": [ "Inferno+", "狱火+" ],
    "StS2 Ironclad-Inflame": [ "Inflame", "燃烧" ],
    "StS2 Ironclad-InflamePlus": [ "Inflame+", "燃烧+" ],
    "StS2 Ironclad-IronWave": [ "Iron Wave", "IronWave", "铁斩波" ],
    "StS2 Ironclad-IronWavePlus": [ "Iron Wave+", "IronWave+", "铁斩波+" ],
    "StS2 Ironclad-Juggernaut": [ "Juggernaut", "势不可当" ],
    "StS2 Ironclad-JuggernautPlus": [ "Juggernaut+", "势不可当+" ],
    "StS2 Ironclad-Juggling": [ "Juggling", "杂耍" ],
    "StS2 Ironclad-JugglingPlus": [ "Juggling+", "杂耍+" ],
    "StS2 Ironclad-Mangle": [ "Mangle", "凌虐" ],
    "StS2 Ironclad-ManglePlus": [ "Mangle+", "凌虐+" ],
    "StS2 Ironclad-Midnight": [ "Midnight", "午夜" ],
    "StS2 Ironclad-MidnightPlus": [ "Midnight+", "午夜+" ],
    "StS2 Ironclad-MoltenFist": [ "Molten Fist", "MoltenFist", "熔融之拳" ],
    "StS2 Ironclad-MoltenFistPlus": [ "Molten Fist+", "MoltenFist+", "熔融之拳+" ],
    "StS2 Ironclad-NotYet": [ "Not Yet", "NotYet", "时候未到" ],
    "StS2 Ironclad-NotYetPlus": [ "Not Yet+", "NotYet+", "时候未到+" ],
    "StS2 Ironclad-Offering": [ "Offering", "祭品" ],
    "StS2 Ironclad-OfferingPlus": [ "Offering+", "祭品+" ],
    "StS2 Ironclad-OneTwoPunch": [ "One-Two Punch", "OneTwoPunch", "连环拳" ],
    "StS2 Ironclad-OneTwoPunchPlus": [ "One-Two Punch+", "OneTwoPunch+", "连环拳+" ],
    "StS2 Ironclad-PactsEnd": [ "Pact's End", "PactsEnd", "契约终结" ],
    "StS2 Ironclad-PactsEndPlus": [ "Pact's End+", "PactsEnd+", "契约终结+" ],
    "StS2 Ironclad-PerfectedStrike": [ "Perfected Strike", "PerfectedStrike", "完美打击" ],
    "StS2 Ironclad-PerfectedStrikePlus": [ "Perfected Strike+", "PerfectedStrike+", "完美打击+" ],
    "StS2 Ironclad-Pillage": [ "Pillage", "劫掠" ],
    "StS2 Ironclad-PillagePlus": [ "Pillage+", "劫掠+" ],
    "StS2 Ironclad-PommelStrike": [ "Pommel Strike", "PommelStrike", "剑柄打击" ],
    "StS2 Ironclad-PommelStrikePlus": [ "Pommel Strike+", "PommelStrike+", "剑柄打击+" ],
    "StS2 Ironclad-PrimalForce": [ "Primal Force", "PrimalForce", "原始力量" ],
    "StS2 Ironclad-PrimalForcePlus": [ "Primal Force+", "PrimalForce+", "原始力量+" ],
    "StS2 Ironclad-Pyre": [ "Pyre", "薪火之源" ],
    "StS2 Ironclad-PyrePlus": [ "Pyre+", "薪火之源+" ],
    "StS2 Ironclad-Rage": [ "Rage", "狂怒" ],
    "StS2 Ironclad-RagePlus": [ "Rage+", "狂怒+" ],
    "StS2 Ironclad-Rampage": [ "Rampage", "暴走" ],
    "StS2 Ironclad-RampagePlus": [ "Rampage+", "暴走+" ],
    "StS2 Ironclad-Rupture": [ "Rupture", "撕裂" ],
    "StS2 Ironclad-RupturePlus": [ "Rupture+", "撕裂+" ],
    "StS2 Ironclad-SecondWind": [ "Second Wind", "SecondWind", "重振精神" ],
    "StS2 Ironclad-SecondWindPlus": [ "Second Wind+", "SecondWind+", "重振精神+" ],
    "StS2 Ironclad-SetupStrike": [ "Setup Strike", "SetupStrike", "预备打击" ],
    "StS2 Ironclad-SetupStrikePlus": [ "Setup Strike+", "SetupStrike+", "预备打击+" ],
    "StS2 Ironclad-ShrugItOff": [ "Shrug It Off", "ShrugItOff", "耸肩无视" ],
    "StS2 Ironclad-ShrugItOffPlus": [ "Shrug It Off+", "ShrugItOff+", "耸肩无视+" ],
    "StS2 Ironclad-Spite": [ "Spite", "怨恨" ],
    "StS2 Ironclad-SpitePlus": [ "Spite+", "怨恨+" ],
    "StS2 Ironclad-Stampede": [ "Stampede", "惊逃" ],
    "StS2 Ironclad-StampedePlus": [ "Stampede+", "惊逃+" ],
    "StS2 Ironclad-Stoke": [ "Stoke", "添柴" ],
    "StS2 Ironclad-StokePlus": [ "Stoke+", "添柴+" ],
    "StS2 Ironclad-Stomp": [ "Stomp", "踩踏" ],
    "StS2 Ironclad-StompPlus": [ "Stomp+", "踩踏+" ],
    "StS2 Ironclad-StoneArmor": [ "Stone Armor", "StoneArmor", "岩石铠甲" ],
    "StS2 Ironclad-StoneArmorPlus": [ "Stone Armor+", "StoneArmor+", "岩石铠甲+" ],
    "StS2 Ironclad-Strike": [ "Strike", "打击" ],
    "StS2 Ironclad-StrikePlus": [ "Strike+", "打击+" ],
    "StS2 Ironclad-SwordBoomerang": [ "Sword Boomerang", "SwordBoomerang", "飞剑回旋镖" ],
    "StS2 Ironclad-SwordBoomerangPlus": [ "Sword Boomerang+", "SwordBoomerang+", "飞剑回旋镖+" ],
    "StS2 Ironclad-Tank": [ "Tank", "肉盾" ],
    "StS2 Ironclad-TankPlus": [ "Tank+", "肉盾+" ],
    "StS2 Ironclad-Taunt": [ "Taunt", "挑衅" ],
    "StS2 Ironclad-TauntPlus": [ "Taunt+", "挑衅+" ],
    "StS2 Ironclad-TearAsunder": [ "Tear Asunder", "TearAsunder", "扯碎" ],
    "StS2 Ironclad-TearAsunderPlus": [ "Tear Asunder+", "TearAsunder+", "扯碎+" ],
    "StS2 Ironclad-Thrash": [ "Thrash", "痛殴" ],
    "StS2 Ironclad-ThrashPlus": [ "Thrash+", "痛殴+" ],
    "StS2 Ironclad-Thunderclap": [ "Thunderclap", "闪电霹雳" ],
    "StS2 Ironclad-ThunderclapPlus": [ "Thunderclap+", "闪电霹雳+" ],
    "StS2 Ironclad-Tremble": [ "Tremble", "战栗" ],
    "StS2 Ironclad-TremblePlus": [ "Tremble+", "战栗+" ],
    "StS2 Ironclad-TrueGrit": [ "True Grit", "TrueGrit", "坚毅" ],
    "StS2 Ironclad-TrueGritPlus": [ "True Grit+", "TrueGrit+", "坚毅+" ],
    "StS2 Ironclad-TwinStrike": [ "Twin Strike", "TwinStrike", "双重打击" ],
    "StS2 Ironclad-TwinStrikePlus": [ "Twin Strike+", "TwinStrike+", "双重打击+" ],
    "StS2 Ironclad-Unmovable": [ "Unmovable", "坚定不移" ],
    "StS2 Ironclad-UnmovablePlus": [ "Unmovable+", "坚定不移+" ],
    "StS2 Ironclad-Unrelenting": [ "Unrelenting", "无情猛攻" ],
    "StS2 Ironclad-UnrelentingPlus": [ "Unrelenting+", "无情猛攻+" ],
    "StS2 Ironclad-Uppercut": [ "Uppercut", "上勾拳" ],
    "StS2 Ironclad-UppercutPlus": [ "Uppercut+", "上勾拳+" ],
    "StS2 Ironclad-Vicious": [ "Vicious", "凶恶" ],
    "StS2 Ironclad-ViciousPlus": [ "Vicious+", "凶恶+" ],
    "StS2 Ironclad-Whirlwind": [ "Whirlwind", "旋风斩" ],
    "StS2 Ironclad-WhirlwindPlus": [ "Whirlwind+", "旋风斩+" ],
    "StS2 Necrobinder-Afterlife": [ "Afterlife", "来生" ],
    "StS2 Necrobinder-AfterlifePlus": [ "Afterlife+", "来生+" ],
    "StS2 Necrobinder-BansheesCry": [ "Banshee's Cry", "BansheesCry", "女妖之嚎" ],
    "StS2 Necrobinder-BansheesCryPlus": [ "Banshee's Cry+", "BansheesCry+", "女妖之嚎+" ],
    "StS2 Necrobinder-BlightStrike": [ "Blight Strike", "BlightStrike", "荒疫打击" ],
    "StS2 Necrobinder-BlightStrikePlus": [ "Blight Strike+", "BlightStrike+", "荒疫打击+" ],
    "StS2 Necrobinder-Bodyguard": [ "Bodyguard", "护卫" ],
    "StS2 Necrobinder-BodyguardPlus": [ "Bodyguard+", "护卫+" ],
    "StS2 Necrobinder-BoneShards": [ "Bone Shards", "BoneShards", "碎骨" ],
    "StS2 Necrobinder-BoneShardsPlus": [ "Bone Shards+", "BoneShards+", "碎骨+" ],
    "StS2 Necrobinder-BorrowedTime": [ "Borrowed Time", "BorrowedTime", "预借时间" ],
    "StS2 Necrobinder-BorrowedTimePlus": [ "Borrowed Time+", "BorrowedTime+", "预借时间+" ],
    "StS2 Necrobinder-Bury": [ "Bury", "埋葬" ],
    "StS2 Necrobinder-BuryPlus": [ "Bury+", "埋葬+" ],
    "StS2 Necrobinder-Calcify": [ "Calcify", "钙化" ],
    "StS2 Necrobinder-CalcifyPlus": [ "Calcify+", "钙化+" ],
    "StS2 Necrobinder-CallOfTheVoid": [ "Call of the Void", "CalloftheVoid", "虚空之唤" ],
    "StS2 Necrobinder-CallOfTheVoidPlus": [ "Call of the Void+", "CalloftheVoid+", "虚空之唤+" ],
    "StS2 Necrobinder-CaptureSpirit": [ "Capture Spirit", "CaptureSpirit", "捕捉灵魂" ],
    "StS2 Necrobinder-CaptureSpiritPlus": [ "Capture Spirit+", "CaptureSpirit+", "捕捉灵魂+" ],
    "StS2 Necrobinder-Cleanse": [ "Cleanse", "洁净" ],
    "StS2 Necrobinder-CleansePlus": [ "Cleanse+", "洁净+" ],
    "StS2 Necrobinder-Countdown": [ "Countdown", "倒数计时" ],
    "StS2 Necrobinder-CountdownPlus": [ "Countdown+", "倒数计时+" ],
    "StS2 Necrobinder-DanseMacabre": [ "Danse Macabre", "DanseMacabre", "死亡之舞" ],
    "StS2 Necrobinder-DanseMacabrePlus": [ "Danse Macabre+", "DanseMacabre+", "死亡之舞+" ],
    "StS2 Necrobinder-Deathbringer": [ "Deathbringer", "死亡使者" ],
    "StS2 Necrobinder-DeathbringerPlus": [ "Deathbringer+", "死亡使者+" ],
    "StS2 Necrobinder-DeathMarch": [ "Death March", "DeathMarch", "死亡行军" ],
    "StS2 Necrobinder-DeathMarchPlus": [ "Death March+", "DeathMarch+", "死亡行军+" ],
    "StS2 Necrobinder-DeathsDoor": [ "Death's Door", "DeathsDoor", "死亡之门" ],
    "StS2 Necrobinder-DeathsDoorPlus": [ "Death's Door+", "DeathsDoor+", "死亡之门+" ],
    "StS2 Necrobinder-Debilitate": [ "Debilitate", "摧残" ],
    "StS2 Necrobinder-DebilitatePlus": [ "Debilitate+", "摧残+" ],
    "StS2 Necrobinder-Defend": [ "Defend", "防御" ],
    "StS2 Necrobinder-DefendPlus": [ "Defend+", "防御+" ],
    "StS2 Necrobinder-Defile": [ "Defile", "玷污" ],
    "StS2 Necrobinder-DefilePlus": [ "Defile+", "玷污+" ],
    "StS2 Necrobinder-Defy": [ "Defy", "违逆" ],
    "StS2 Necrobinder-DefyPlus": [ "Defy+", "违逆+" ],
    "StS2 Necrobinder-Delay": [ "Delay", "拖延" ],
    "StS2 Necrobinder-DelayPlus": [ "Delay+", "拖延+" ],
    "StS2 Necrobinder-Demesne": [ "Demesne", "领域" ],
    "StS2 Necrobinder-DemesnePlus": [ "Demesne+", "领域+" ],
    "StS2 Necrobinder-DevourLife": [ "Devour Life", "DevourLife", "吞噬生命" ],
    "StS2 Necrobinder-DevourLifePlus": [ "Devour Life+", "DevourLife+", "吞噬生命+" ],
    "StS2 Necrobinder-Dirge": [ "Dirge", "挽歌" ],
    "StS2 Necrobinder-DirgePlus": [ "Dirge+", "挽歌+" ],
    "StS2 Necrobinder-DrainPower": [ "Drain Power", "DrainPower", "能量汲取" ],
    "StS2 Necrobinder-DrainPowerPlus": [ "Drain Power+", "DrainPower+", "能量汲取+" ],
    "StS2 Necrobinder-Dredge": [ "Dredge", "清淤" ],
    "StS2 Necrobinder-DredgePlus": [ "Dredge+", "清淤+" ],
    "StS2 Necrobinder-Eidolon": [ "Eidolon", "幻景" ],
    "StS2 Necrobinder-EidolonPlus": [ "Eidolon+", "幻景+" ],
    "StS2 Necrobinder-EndOfDays": [ "End of Days", "EndofDays", "末日降临" ],
    "StS2 Necrobinder-EndOfDaysPlus": [ "End of Days+", "EndofDays+", "末日降临+" ],
    "StS2 Necrobinder-EnfeeblingTouch": [ "Enfeebling Touch", "EnfeeblingTouch", "弱化之触" ],
    "StS2 Necrobinder-EnfeeblingTouchPlus": [ "Enfeebling Touch+", "EnfeeblingTouch+", "弱化之触+" ],
    "StS2 Necrobinder-Eradicate": [ "Eradicate", "根除" ],
    "StS2 Necrobinder-EradicatePlus": [ "Eradicate+", "根除+" ],
    "StS2 Necrobinder-Fear": [ "Fear", "恐惧" ],
    "StS2 Necrobinder-FearPlus": [ "Fear+", "恐惧+" ],
    "StS2 Necrobinder-Fetch": [ "Fetch", "取回" ],
    "StS2 Necrobinder-FetchPlus": [ "Fetch+", "取回+" ],
    "StS2 Necrobinder-Flatten": [ "Flatten", "重压" ],
    "StS2 Necrobinder-FlattenPlus": [ "Flatten+", "重压+" ],
    "StS2 Necrobinder-ForbiddenGrimoire": [ "Forbidden Grimoire", "ForbiddenGrimoire", "禁忌魔典" ],
    "StS2 Necrobinder-ForbiddenGrimoirePlus": [ "Forbidden Grimoire+", "ForbiddenGrimoire+", "禁忌魔典+" ],
    "StS2 Necrobinder-Friendship": [ "Friendship", "友谊" ],
    "StS2 Necrobinder-FriendshipPlus": [ "Friendship+", "友谊+" ],
    "StS2 Necrobinder-GlimpseBeyond": [ "Glimpse Beyond", "GlimpseBeyond", "彼岸一瞥" ],
    "StS2 Necrobinder-GlimpseBeyondPlus": [ "Glimpse Beyond+", "GlimpseBeyond+", "彼岸一瞥+" ],
    "StS2 Necrobinder-Graveblast": [ "Graveblast", "坟冢爆射" ],
    "StS2 Necrobinder-GraveblastPlus": [ "Graveblast+", "坟冢爆射+" ],
    "StS2 Necrobinder-GraveWarden": [ "Grave Warden", "GraveWarden", "守墓人" ],
    "StS2 Necrobinder-GraveWardenPlus": [ "Grave Warden+", "GraveWarden+", "守墓人+" ],
    "StS2 Necrobinder-Hang": [ "Hang", "吊杀" ],
    "StS2 Necrobinder-HangPlus": [ "Hang+", "吊杀+" ],
    "StS2 Necrobinder-Haunt": [ "Haunt", "纠缠" ],
    "StS2 Necrobinder-HauntPlus": [ "Haunt+", "纠缠+" ],
    "StS2 Necrobinder-HighFive": [ "High Five", "HighFive", "击掌" ],
    "StS2 Necrobinder-HighFivePlus": [ "High Five+", "HighFive+", "击掌+" ],
    "StS2 Necrobinder-Invoke": [ "Invoke", "唤起" ],
    "StS2 Necrobinder-InvokePlus": [ "Invoke+", "唤起+" ],
    "StS2 Necrobinder-LegionOfBone": [ "Legion of Bone", "LegionofBone", "骸骨军团" ],
    "StS2 Necrobinder-LegionOfBonePlus": [ "Legion of Bone+", "LegionofBone+", "骸骨军团+" ],
    "StS2 Necrobinder-Lethality": [ "Lethality", "致死性" ],
    "StS2 Necrobinder-LethalityPlus": [ "Lethality+", "致死性+" ],
    "StS2 Necrobinder-Melancholy": [ "Melancholy", "忧郁" ],
    "StS2 Necrobinder-MelancholyPlus": [ "Melancholy+", "忧郁+" ],
    "StS2 Necrobinder-Misery": [ "Misery", "苦难" ],
    "StS2 Necrobinder-MiseryPlus": [ "Misery+", "苦难+" ],
    "StS2 Necrobinder-NecroMastery": [ "Necro Mastery", "NecroMastery", "亡灵精通" ],
    "StS2 Necrobinder-NecroMasteryPlus": [ "Necro Mastery+", "NecroMastery+", "亡灵精通+" ],
    "StS2 Necrobinder-NegativePulse": [ "Negative Pulse", "NegativePulse", "负能量脉冲" ],
    "StS2 Necrobinder-NegativePulsePlus": [ "Negative Pulse+", "NegativePulse+", "负能量脉冲+" ],
    "StS2 Necrobinder-Neurosurge": [ "Neurosurge", "精神过载" ],
    "StS2 Necrobinder-NeurosurgePlus": [ "Neurosurge+", "精神过载+" ],
    "StS2 Necrobinder-NoEscape": [ "No Escape", "NoEscape", "无处可逃" ],
    "StS2 Necrobinder-NoEscapePlus": [ "No Escape+", "NoEscape+", "无处可逃+" ],
    "StS2 Necrobinder-Oblivion": [ "Oblivion", "湮灭" ],
    "StS2 Necrobinder-OblivionPlus": [ "Oblivion+", "湮灭+" ],
    "StS2 Necrobinder-Pagestorm": [ "Pagestorm", "书页风暴" ],
    "StS2 Necrobinder-PagestormPlus": [ "Pagestorm+", "书页风暴+" ],
    "StS2 Necrobinder-Parse": [ "Parse", "领会" ],
    "StS2 Necrobinder-ParsePlus": [ "Parse+", "领会+" ],
    "StS2 Necrobinder-Poke": [ "Poke", "戳击" ],
    "StS2 Necrobinder-PokePlus": [ "Poke+", "戳击+" ],
    "StS2 Necrobinder-Protector": [ "Protector", "守护者" ],
    "StS2 Necrobinder-ProtectorPlus": [ "Protector+", "守护者+" ],
    "StS2 Necrobinder-PullAggro": [ "Pull Aggro", "PullAggro", "吸引仇恨" ],
    "StS2 Necrobinder-PullAggroPlus": [ "Pull Aggro+", "PullAggro+", "吸引仇恨+" ],
    "StS2 Necrobinder-PullFromBelow": [ "Pull from Below", "PullfromBelow", "亡魂牵引" ],
    "StS2 Necrobinder-PullFromBelowPlus": [ "Pull from Below+", "PullfromBelow+", "亡魂牵引+" ],
    "StS2 Necrobinder-Putrefy": [ "Putrefy", "腐败" ],
    "StS2 Necrobinder-PutrefyPlus": [ "Putrefy+", "腐败+" ],
    "StS2 Necrobinder-Rattle": [ "Rattle", "猛晃" ],
    "StS2 Necrobinder-RattlePlus": [ "Rattle+", "猛晃+" ],
    "StS2 Necrobinder-Reanimate": [ "Reanimate", "死者苏生" ],
    "StS2 Necrobinder-ReanimatePlus": [ "Reanimate+", "死者苏生+" ],
    "StS2 Necrobinder-Reap": [ "Reap", "收割" ],
    "StS2 Necrobinder-ReaperForm": [ "Reaper Form", "ReaperForm", "死神形态" ],
    "StS2 Necrobinder-ReaperFormPlus": [ "Reaper Form+", "ReaperForm+", "死神形态+" ],
    "StS2 Necrobinder-ReapPlus": [ "Reap+", "收割+" ],
    "StS2 Necrobinder-Reave": [ "Reave", "剥夺" ],
    "StS2 Necrobinder-ReavePlus": [ "Reave+", "剥夺+" ],
    "StS2 Necrobinder-RightHandHand": [ "Right Hand Hand", "RightHandHand", "得力助手" ],
    "StS2 Necrobinder-RightHandHandPlus": [ "Right Hand Hand+", "RightHandHand+", "得力助手+" ],
    "StS2 Necrobinder-Sacrifice": [ "Sacrifice", "牺牲" ],
    "StS2 Necrobinder-SacrificePlus": [ "Sacrifice+", "牺牲+" ],
    "StS2 Necrobinder-Scourge": [ "Scourge", "鞭打" ],
    "StS2 Necrobinder-ScourgePlus": [ "Scourge+", "鞭打+" ],
    "StS2 Necrobinder-SculptingStrike": [ "Sculpting Strike", "SculptingStrike", "雕琢打击" ],
    "StS2 Necrobinder-SculptingStrikePlus": [ "Sculpting Strike+", "SculptingStrike+", "雕琢打击+" ],
    "StS2 Necrobinder-Seance": [ "Seance", "降灵" ],
    "StS2 Necrobinder-SeancePlus": [ "Seance+", "降灵+" ],
    "StS2 Necrobinder-SentryMode": [ "Sentry Mode", "SentryMode", "哨卫模式" ],
    "StS2 Necrobinder-SentryModePlus": [ "Sentry Mode+", "SentryMode+", "哨卫模式+" ],
    "StS2 Necrobinder-Severance": [ "Severance", "切断" ],
    "StS2 Necrobinder-SeverancePlus": [ "Severance+", "切断+" ],
    "StS2 Necrobinder-SharedFate": [ "Shared Fate", "SharedFate", "命运同担" ],
    "StS2 Necrobinder-SharedFatePlus": [ "Shared Fate+", "SharedFate+", "命运同担+" ],
    "StS2 Necrobinder-Shroud": [ "Shroud", "厄运之衣" ],
    "StS2 Necrobinder-ShroudPlus": [ "Shroud+", "厄运之衣+" ],
    "StS2 Necrobinder-SicEm": [ "Sic 'Em", "SicEm", "紧追不放" ],
    "StS2 Necrobinder-SicEmPlus": [ "Sic 'Em+", "SicEm+", "紧追不放+" ],
    "StS2 Necrobinder-SleightOfFlesh": [ "Sleight of Flesh", "SleightofFlesh", "血肉戏法" ],
    "StS2 Necrobinder-SleightOfFleshPlus": [ "Sleight of Flesh+", "SleightofFlesh+", "血肉戏法+" ],
    "StS2 Necrobinder-Snap": [ "Snap", "响指" ],
    "StS2 Necrobinder-SnapPlus": [ "Snap+", "响指+" ],
    "StS2 Necrobinder-SoulStorm": [ "Soul Storm", "SoulStorm", "灵魂风暴" ],
    "StS2 Necrobinder-SoulStormPlus": [ "Soul Storm+", "SoulStorm+", "灵魂风暴+" ],
    "StS2 Necrobinder-Sow": [ "Sow", "播种" ],
    "StS2 Necrobinder-SowPlus": [ "Sow+", "播种+" ],
    "StS2 Necrobinder-SpiritOfAsh": [ "Spirit of Ash", "SpiritofAsh", "灰烬之灵" ],
    "StS2 Necrobinder-SpiritOfAshPlus": [ "Spirit of Ash+", "SpiritofAsh+", "灰烬之灵+" ],
    "StS2 Necrobinder-Spur": [ "Spur", "增生" ],
    "StS2 Necrobinder-SpurPlus": [ "Spur+", "增生+" ],
    "StS2 Necrobinder-Squeeze": [ "Squeeze", "榨取" ],
    "StS2 Necrobinder-SqueezePlus": [ "Squeeze+", "榨取+" ],
    "StS2 Necrobinder-Strike": [ "Strike", "打击" ],
    "StS2 Necrobinder-StrikePlus": [ "Strike+", "打击+" ],
    "StS2 Necrobinder-TheScythe": [ "The Scythe", "TheScythe", "巨镰" ],
    "StS2 Necrobinder-TheScythePlus": [ "The Scythe+", "TheScythe+", "巨镰+" ],
    "StS2 Necrobinder-TimesUp": [ "Time's Up", "TimesUp", "大限已至" ],
    "StS2 Necrobinder-TimesUpPlus": [ "Time's Up+", "TimesUp+", "大限已至+" ],
    "StS2 Necrobinder-Transfigure": [ "Transfigure", "重构" ],
    "StS2 Necrobinder-TransfigurePlus": [ "Transfigure+", "重构+" ],
    "StS2 Necrobinder-Undeath": [ "Undeath", "不死" ],
    "StS2 Necrobinder-UndeathPlus": [ "Undeath+", "不死+" ],
    "StS2 Necrobinder-Unleash": [ "Unleash", "出击" ],
    "StS2 Necrobinder-UnleashPlus": [ "Unleash+", "出击+" ],
    "StS2 Necrobinder-Veilpiercer": [ "Veilpiercer", "刺破帷幕" ],
    "StS2 Necrobinder-VeilpiercerPlus": [ "Veilpiercer+", "刺破帷幕+" ],
    "StS2 Necrobinder-Wisp": [ "Wisp", "鬼火" ],
    "StS2 Necrobinder-WispPlus": [ "Wisp+", "鬼火+" ],
    "StS2 Quest-ByrdonisEgg": [ "Byrdonis Egg", "ByrdonisEgg", "多尼斯异鸟蛋" ],
    "StS2 Quest-Dowsing": [ "Dowsing", "探寻" ],
    "StS2 Quest-LanternKey": [ "Lantern Key", "LanternKey", "灯火钥匙" ],
    "StS2 Quest-SpoilsMap": [ "Spoils Map", "SpoilsMap", "藏宝图" ],
    "StS2 Regent-Alignment": [ "Alignment", "星位序列" ],
    "StS2 Regent-AlignmentPlus": [ "Alignment+", "星位序列+" ],
    "StS2 Regent-Arsenal": [ "Arsenal", "武器库" ],
    "StS2 Regent-ArsenalPlus": [ "Arsenal+", "武器库+" ],
    "StS2 Regent-AstralPulse": [ "Astral Pulse", "AstralPulse", "星界脉冲" ],
    "StS2 Regent-AstralPulsePlus": [ "Astral Pulse+", "AstralPulse+", "星界脉冲+" ],
    "StS2 Regent-BeatIntoShape": [ "Beat into Shape", "BeatintoShape", "锻打成型" ],
    "StS2 Regent-BeatIntoShapePlus": [ "Beat into Shape+", "BeatintoShape+", "锻打成型+" ],
    "StS2 Regent-BEGONE": [ "BEGONE!", "下去！" ],
    "StS2 Regent-BEGONEPlus": [ "BEGONE!+", "下去！+" ],
    "StS2 Regent-BigBang": [ "Big Bang", "BigBang", "大爆炸" ],
    "StS2 Regent-BigBangPlus": [ "Big Bang+", "BigBang+", "大爆炸+" ],
    "StS2 Regent-BlackHole": [ "Black Hole", "BlackHole", "黑洞" ],
    "StS2 Regent-BlackHolePlus": [ "Black Hole+", "BlackHole+", "黑洞+" ],
    "StS2 Regent-Bombardment": [ "Bombardment", "轰击" ],
    "StS2 Regent-BombardmentPlus": [ "Bombardment+", "轰击+" ],
    "StS2 Regent-Bulwark": [ "Bulwark", "铸墙" ],
    "StS2 Regent-BulwarkPlus": [ "Bulwark+", "铸墙+" ],
    "StS2 Regent-BundleOfJoy": [ "Bundle of Joy", "BundleofJoy", "新生之喜" ],
    "StS2 Regent-BundleOfJoyPlus": [ "Bundle of Joy+", "BundleofJoy+", "新生之喜+" ],
    "StS2 Regent-CelestialMight": [ "Celestial Might", "CelestialMight", "天穹之力" ],
    "StS2 Regent-CelestialMightPlus": [ "Celestial Might+", "CelestialMight+", "天穹之力+" ],
    "StS2 Regent-CHARGE": [ "CHARGE!!", "冲锋！！" ],
    "StS2 Regent-CHARGEPlus": [ "CHARGE!!+", "冲锋！！+" ],
    "StS2 Regent-ChildOfTheStars": [ "Child of the Stars", "ChildoftheStars", "群星之子" ],
    "StS2 Regent-ChildOfTheStarsPlus": [ "Child of the Stars+", "ChildoftheStars+", "群星之子+" ],
    "StS2 Regent-CloakOfStars": [ "Cloak of Stars", "CloakofStars", "群星斗篷" ],
    "StS2 Regent-CloakOfStarsPlus": [ "Cloak of Stars+", "CloakofStars+", "群星斗篷+" ],
    "StS2 Regent-CollisionCourse": [ "Collision Course", "CollisionCourse", "碰撞轨迹" ],
    "StS2 Regent-CollisionCoursePlus": [ "Collision Course+", "CollisionCourse+", "碰撞轨迹+" ],
    "StS2 Regent-Comet": [ "Comet", "彗星" ],
    "StS2 Regent-CometPlus": [ "Comet+", "彗星+" ],
    "StS2 Regent-Conqueror": [ "Conqueror", "征服者" ],
    "StS2 Regent-ConquerorPlus": [ "Conqueror+", "征服者+" ],
    "StS2 Regent-Convergence": [ "Convergence", "汇流" ],
    "StS2 Regent-ConvergencePlus": [ "Convergence+", "汇流+" ],
    "StS2 Regent-CosmicIndifference": [ "Cosmic Indifference", "CosmicIndifference", "宇宙冷漠" ],
    "StS2 Regent-CosmicIndifferencePlus": [ "Cosmic Indifference+", "CosmicIndifference+", "宇宙冷漠+" ],
    "StS2 Regent-CrashLanding": [ "Crash Landing", "CrashLanding", "迫降" ],
    "StS2 Regent-CrashLandingPlus": [ "Crash Landing+", "CrashLanding+", "迫降+" ],
    "StS2 Regent-CrescentSpear": [ "Crescent Spear", "CrescentSpear", "新月长矛" ],
    "StS2 Regent-CrescentSpearPlus": [ "Crescent Spear+", "CrescentSpear+", "新月长矛+" ],
    "StS2 Regent-CrushUnder": [ "Crush Under", "CrushUnder", "下砸" ],
    "StS2 Regent-CrushUnderPlus": [ "Crush Under+", "CrushUnder+", "下砸+" ],
    "StS2 Regent-DecisionsDecisions": [ "Decisions, Decisions", "Decisions,Decisions", "抉择，抉择" ],
    "StS2 Regent-DecisionsDecisionsPlus": [ "Decisions, Decisions+", "Decisions,Decisions+", "抉择，抉择+" ],
    "StS2 Regent-Defend": [ "Defend", "防御" ],
    "StS2 Regent-DefendPlus": [ "Defend+", "防御+" ],
    "StS2 Regent-Devastate": [ "Devastate", "葬送" ],
    "StS2 Regent-DevastatePlus": [ "Devastate+", "葬送+" ],
    "StS2 Regent-DyingStar": [ "Dying Star", "DyingStar", "星灭" ],
    "StS2 Regent-DyingStarPlus": [ "Dying Star+", "DyingStar+", "星灭+" ],
    "StS2 Regent-FallingStar": [ "Falling Star", "FallingStar", "陨星" ],
    "StS2 Regent-FallingStarPlus": [ "Falling Star+", "FallingStar+", "陨星+" ],
    "StS2 Regent-ForegoneConclusion": [ "Foregone Conclusion", "ForegoneConclusion", "既定事项" ],
    "StS2 Regent-ForegoneConclusionPlus": [ "Foregone Conclusion+", "ForegoneConclusion+", "既定事项+" ],
    "StS2 Regent-Furnace": [ "Furnace", "熔炉" ],
    "StS2 Regent-FurnacePlus": [ "Furnace+", "熔炉+" ],
    "StS2 Regent-GammaBlast": [ "Gamma Blast", "GammaBlast", "伽马爆破" ],
    "StS2 Regent-GammaBlastPlus": [ "Gamma Blast+", "GammaBlast+", "伽马爆破+" ],
    "StS2 Regent-GatherLight": [ "Gather Light", "GatherLight", "收集光辉" ],
    "StS2 Regent-GatherLightPlus": [ "Gather Light+", "GatherLight+", "收集光辉+" ],
    "StS2 Regent-Genesis": [ "Genesis", "创世纪" ],
    "StS2 Regent-GenesisPlus": [ "Genesis+", "创世纪+" ],
    "StS2 Regent-Glimmer": [ "Glimmer", "微光" ],
    "StS2 Regent-GlimmerPlus": [ "Glimmer+", "微光+" ],
    "StS2 Regent-Glitterstream": [ "Glitterstream", "流光溢彩" ],
    "StS2 Regent-GlitterstreamPlus": [ "Glitterstream+", "流光溢彩+" ],
    "StS2 Regent-Glow": [ "Glow", "辉光" ],
    "StS2 Regent-GlowPlus": [ "Glow+", "辉光+" ],
    "StS2 Regent-GUARDS": [ "GUARDS!!!", "护驾！！！" ],
    "StS2 Regent-GUARDSPlus": [ "GUARDS!!!+", "护驾！！！+" ],
    "StS2 Regent-GuidingStar": [ "Guiding Star", "GuidingStar", "引导之星" ],
    "StS2 Regent-GuidingStarPlus": [ "Guiding Star+", "GuidingStar+", "引导之星+" ],
    "StS2 Regent-HammerTime": [ "Hammer Time", "HammerTime", "锤子时间" ],
    "StS2 Regent-HammerTimePlus": [ "Hammer Time+", "HammerTime+", "锤子时间+" ],
    "StS2 Regent-HeavenlyDrill": [ "Heavenly Drill", "HeavenlyDrill", "天际钻头" ],
    "StS2 Regent-HeavenlyDrillPlus": [ "Heavenly Drill+", "HeavenlyDrill+", "天际钻头+" ],
    "StS2 Regent-Hegemony": [ "Hegemony", "霸权" ],
    "StS2 Regent-HegemonyPlus": [ "Hegemony+", "霸权+" ],
    "StS2 Regent-HeirloomHammer": [ "Heirloom Hammer", "HeirloomHammer", "传承之锤" ],
    "StS2 Regent-HeirloomHammerPlus": [ "Heirloom Hammer+", "HeirloomHammer+", "传承之锤+" ],
    "StS2 Regent-HiddenCache": [ "Hidden Cache", "HiddenCache", "隐秘藏品" ],
    "StS2 Regent-HiddenCachePlus": [ "Hidden Cache+", "HiddenCache+", "隐秘藏品+" ],
    "StS2 Regent-IAmInvincible": [ "I Am Invincible", "IAmInvincible", "所向无敌" ],
    "StS2 Regent-IAmInvinciblePlus": [ "I Am Invincible+", "IAmInvincible+", "所向无敌+" ],
    "StS2 Regent-KinglyKick": [ "Kingly Kick", "KinglyKick", "王者之踢" ],
    "StS2 Regent-KinglyKickPlus": [ "Kingly Kick+", "KinglyKick+", "王者之踢+" ],
    "StS2 Regent-KinglyPunch": [ "Kingly Punch", "KinglyPunch", "王者之拳" ],
    "StS2 Regent-KinglyPunchPlus": [ "Kingly Punch+", "KinglyPunch+", "王者之拳+" ],
    "StS2 Regent-KnockoutBlow": [ "Knockout Blow", "KnockoutBlow", "决胜一击" ],
    "StS2 Regent-KnockoutBlowPlus": [ "Knockout Blow+", "KnockoutBlow+", "决胜一击+" ],
    "StS2 Regent-KnowThyPlace": [ "Know Thy Place", "KnowThyPlace", "何人僭越" ],
    "StS2 Regent-KnowThyPlacePlus": [ "Know Thy Place+", "KnowThyPlace+", "何人僭越+" ],
    "StS2 Regent-Largesse": [ "Largesse", "慷慨捐助" ],
    "StS2 Regent-LargessePlus": [ "Largesse+", "慷慨捐助+" ],
    "StS2 Regent-LunarBlast": [ "Lunar Blast", "LunarBlast", "月面射击" ],
    "StS2 Regent-LunarBlastPlus": [ "Lunar Blast+", "LunarBlast+", "月面射击+" ],
    "StS2 Regent-MakeItSo": [ "Make It So", "MakeItSo", "如此甚好" ],
    "StS2 Regent-MakeItSoPlus": [ "Make It So+", "MakeItSo+", "如此甚好+" ],
    "StS2 Regent-ManifestAuthority": [ "Manifest Authority", "ManifestAuthority", "君权自授" ],
    "StS2 Regent-ManifestAuthorityPlus": [ "Manifest Authority+", "ManifestAuthority+", "君权自授+" ],
    "StS2 Regent-MeteorShower": [ "Meteor Shower", "MeteorShower", "流星雨" ],
    "StS2 Regent-MeteorShowerPlus": [ "Meteor Shower+", "MeteorShower+", "流星雨+" ],
    "StS2 Regent-MonarchsGaze": [ "Monarch's Gaze", "MonarchsGaze", "王之凝视" ],
    "StS2 Regent-MonarchsGazePlus": [ "Monarch's Gaze+", "MonarchsGaze+", "王之凝视+" ],
    "StS2 Regent-Monologue": [ "Monologue", "独白" ],
    "StS2 Regent-MonologuePlus": [ "Monologue+", "独白+" ],
    "StS2 Regent-NeutronAegis": [ "Neutron Aegis", "NeutronAegis", "中子护盾" ],
    "StS2 Regent-NeutronAegisPlus": [ "Neutron Aegis+", "NeutronAegis+", "中子护盾+" ],
    "StS2 Regent-Orbit": [ "Orbit", "环绕轨道" ],
    "StS2 Regent-OrbitPlus": [ "Orbit+", "环绕轨道+" ],
    "StS2 Regent-PaleBlueDot": [ "Pale Blue Dot", "PaleBlueDot", "暗淡蓝点" ],
    "StS2 Regent-PaleBlueDotPlus": [ "Pale Blue Dot+", "PaleBlueDot+", "暗淡蓝点+" ],
    "StS2 Regent-Parry": [ "Parry", "招架" ],
    "StS2 Regent-ParryPlus": [ "Parry+", "招架+" ],
    "StS2 Regent-ParticleWall": [ "Particle Wall", "ParticleWall", "粒子墙" ],
    "StS2 Regent-ParticleWallPlus": [ "Particle Wall+", "ParticleWall+", "粒子墙+" ],
    "StS2 Regent-Patter": [ "Patter", "星星点点" ],
    "StS2 Regent-PatterPlus": [ "Patter+", "星星点点+" ],
    "StS2 Regent-PhotonCut": [ "Photon Cut", "PhotonCut", "光子切割" ],
    "StS2 Regent-PhotonCutPlus": [ "Photon Cut+", "PhotonCut+", "光子切割+" ],
    "StS2 Regent-PillarOfCreation": [ "Pillar of Creation", "PillarofCreation", "创世之柱" ],
    "StS2 Regent-PillarOfCreationPlus": [ "Pillar of Creation+", "PillarofCreation+", "创世之柱+" ],
    "StS2 Regent-Prophesize": [ "Prophesize", "预言" ],
    "StS2 Regent-ProphesizePlus": [ "Prophesize+", "预言+" ],
    "StS2 Regent-Quasar": [ "Quasar", "类星体" ],
    "StS2 Regent-QuasarPlus": [ "Quasar+", "类星体+" ],
    "StS2 Regent-Radiate": [ "Radiate", "辐射" ],
    "StS2 Regent-RadiatePlus": [ "Radiate+", "辐射+" ],
    "StS2 Regent-RefineBlade": [ "Refine Blade", "RefineBlade", "淬炼刀刃" ],
    "StS2 Regent-RefineBladePlus": [ "Refine Blade+", "RefineBlade+", "淬炼刀刃+" ],
    "StS2 Regent-Reflect": [ "Reflect", "倒映" ],
    "StS2 Regent-ReflectPlus": [ "Reflect+", "倒映+" ],
    "StS2 Regent-Resonance": [ "Resonance", "共鸣" ],
    "StS2 Regent-ResonancePlus": [ "Resonance+", "共鸣+" ],
    "StS2 Regent-RoyalGamble": [ "Royal Gamble", "RoyalGamble", "胜券在王" ],
    "StS2 Regent-RoyalGamblePlus": [ "Royal Gamble+", "RoyalGamble+", "胜券在王+" ],
    "StS2 Regent-Royalties": [ "Royalties", "王国资产" ],
    "StS2 Regent-RoyaltiesPlus": [ "Royalties+", "王国资产+" ],
    "StS2 Regent-SeekingEdge": [ "Seeking Edge", "SeekingEdge", "追踪之刃" ],
    "StS2 Regent-SeekingEdgePlus": [ "Seeking Edge+", "SeekingEdge+", "追踪之刃+" ],
    "StS2 Regent-SevenStars": [ "Seven Stars", "SevenStars", "七星" ],
    "StS2 Regent-SevenStarsPlus": [ "Seven Stars+", "SevenStars+", "七星+" ],
    "StS2 Regent-ShiningStrike": [ "Shining Strike", "ShiningStrike", "明耀打击" ],
    "StS2 Regent-ShiningStrikePlus": [ "Shining Strike+", "ShiningStrike+", "明耀打击+" ],
    "StS2 Regent-SolarStrike": [ "Solar Strike", "SolarStrike", "太阳打击" ],
    "StS2 Regent-SolarStrikePlus": [ "Solar Strike+", "SolarStrike+", "太阳打击+" ],
    "StS2 Regent-SpectrumShift": [ "Spectrum Shift", "SpectrumShift", "光谱偏移" ],
    "StS2 Regent-SpectrumShiftPlus": [ "Spectrum Shift+", "SpectrumShift+", "光谱偏移+" ],
    "StS2 Regent-SpoilsOfBattle": [ "Spoils of Battle", "SpoilsofBattle", "战利品" ],
    "StS2 Regent-SpoilsOfBattlePlus": [ "Spoils of Battle+", "SpoilsofBattle+", "战利品+" ],
    "StS2 Regent-Stardust": [ "Stardust", "星尘" ],
    "StS2 Regent-StardustPlus": [ "Stardust+", "星尘+" ],
    "StS2 Regent-Strike": [ "Strike", "打击" ],
    "StS2 Regent-StrikePlus": [ "Strike+", "打击+" ],
    "StS2 Regent-SummonForth": [ "Summon Forth", "SummonForth", "征召上前" ],
    "StS2 Regent-SummonForthPlus": [ "Summon Forth+", "SummonForth+", "征召上前+" ],
    "StS2 Regent-Supermassive": [ "Supermassive", "超质量体" ],
    "StS2 Regent-SupermassivePlus": [ "Supermassive+", "超质量体+" ],
    "StS2 Regent-SwordSage": [ "Sword Sage", "SwordSage", "剑圣" ],
    "StS2 Regent-SwordSagePlus": [ "Sword Sage+", "SwordSage+", "剑圣+" ],
    "StS2 Regent-Terraforming": [ "Terraforming", "地形改造" ],
    "StS2 Regent-TerraformingPlus": [ "Terraforming+", "地形改造+" ],
    "StS2 Regent-TheSealedThrone": [ "The Sealed Throne", "TheSealedThrone", "封印王座" ],
    "StS2 Regent-TheSealedThronePlus": [ "The Sealed Throne+", "TheSealedThrone+", "封印王座+" ],
    "StS2 Regent-TheSmith": [ "The Smith", "TheSmith", "铸剑者" ],
    "StS2 Regent-TheSmithPlus": [ "The Smith+", "TheSmith+", "铸剑者+" ],
    "StS2 Regent-Tutor": [ "Tutor", "指导" ],
    "StS2 Regent-TutorPlus": [ "Tutor+", "指导+" ],
    "StS2 Regent-Tyranny": [ "Tyranny", "暴政" ],
    "StS2 Regent-TyrannyPlus": [ "Tyranny+", "暴政+" ],
    "StS2 Regent-Venerate": [ "Venerate", "崇拜" ],
    "StS2 Regent-VeneratePlus": [ "Venerate+", "崇拜+" ],
    "StS2 Regent-VoidForm": [ "Void Form", "VoidForm", "虚空形态" ],
    "StS2 Regent-VoidFormPlus": [ "Void Form+", "VoidForm+", "虚空形态+" ],
    "StS2 Regent-WroughtInWar": [ "Wrought in War", "WroughtinWar", "战火铸就" ],
    "StS2 Regent-WroughtInWarPlus": [ "Wrought in War+", "WroughtinWar+", "战火铸就+" ],
    "StS2 Silent-Abrasive": [ "Abrasive", "磨蚀" ],
    "StS2 Silent-AbrasivePlus": [ "Abrasive+", "磨蚀+" ],
    "StS2 Silent-Accelerant": [ "Accelerant", "触媒" ],
    "StS2 Silent-AccelerantPlus": [ "Accelerant+", "触媒+" ],
    "StS2 Silent-Accuracy": [ "Accuracy", "精准" ],
    "StS2 Silent-AccuracyPlus": [ "Accuracy+", "精准+" ],
    "StS2 Silent-Acrobatics": [ "Acrobatics", "杂技" ],
    "StS2 Silent-AcrobaticsPlus": [ "Acrobatics+", "杂技+" ],
    "StS2 Silent-Adrenaline": [ "Adrenaline", "肾上腺素" ],
    "StS2 Silent-AdrenalinePlus": [ "Adrenaline+", "肾上腺素+" ],
    "StS2 Silent-Afterimage": [ "Afterimage", "余像" ],
    "StS2 Silent-AfterimagePlus": [ "Afterimage+", "余像+" ],
    "StS2 Silent-Anticipate": [ "Anticipate", "预判" ],
    "StS2 Silent-AnticipatePlus": [ "Anticipate+", "预判+" ],
    "StS2 Silent-Assassinate": [ "Assassinate", "刺杀" ],
    "StS2 Silent-AssassinatePlus": [ "Assassinate+", "刺杀+" ],
    "StS2 Silent-Backflip": [ "Backflip", "后空翻" ],
    "StS2 Silent-BackflipPlus": [ "Backflip+", "后空翻+" ],
    "StS2 Silent-Backstab": [ "Backstab", "背刺" ],
    "StS2 Silent-BackstabPlus": [ "Backstab+", "背刺+" ],
    "StS2 Silent-BladeDance": [ "Blade Dance", "BladeDance", "刀刃之舞" ],
    "StS2 Silent-BladeDancePlus": [ "Blade Dance+", "BladeDance+", "刀刃之舞+" ],
    "StS2 Silent-BladeOfInk": [ "Blade of Ink", "BladeofInk", "墨之刃" ],
    "StS2 Silent-BladeOfInkPlus": [ "Blade of Ink+", "BladeofInk+", "墨之刃+" ],
    "StS2 Silent-Blur": [ "Blur", "残影" ],
    "StS2 Silent-BlurPlus": [ "Blur+", "残影+" ],
    "StS2 Silent-BouncingFlask": [ "Bouncing Flask", "BouncingFlask", "弹跳药瓶" ],
    "StS2 Silent-BouncingFlaskPlus": [ "Bouncing Flask+", "BouncingFlask+", "弹跳药瓶+" ],
    "StS2 Silent-BubbleBubble": [ "Bubble Bubble", "BubbleBubble", "咕嘟冒泡" ],
    "StS2 Silent-BubbleBubblePlus": [ "Bubble Bubble+", "BubbleBubble+", "咕嘟冒泡+" ],
    "StS2 Silent-BulletTime": [ "Bullet Time", "BulletTime", "子弹时间" ],
    "StS2 Silent-BulletTimePlus": [ "Bullet Time+", "BulletTime+", "子弹时间+" ],
    "StS2 Silent-Burst": [ "Burst", "爆发" ],
    "StS2 Silent-BurstPlus": [ "Burst+", "爆发+" ],
    "StS2 Silent-CalculatedGamble": [ "Calculated Gamble", "CalculatedGamble", "计算下注" ],
    "StS2 Silent-CalculatedGamblePlus": [ "Calculated Gamble+", "CalculatedGamble+", "计算下注+" ],
    "StS2 Silent-CloakAndDagger": [ "Cloak and Dagger", "CloakandDagger", "斗篷与匕首" ],
    "StS2 Silent-CloakAndDaggerPlus": [ "Cloak and Dagger+", "CloakandDagger+", "斗篷与匕首+" ],
    "StS2 Silent-CorrosiveWave": [ "Corrosive Wave", "CorrosiveWave", "腐蚀波" ],
    "StS2 Silent-CorrosiveWavePlus": [ "Corrosive Wave+", "CorrosiveWave+", "腐蚀波+" ],
    "StS2 Silent-DaggerSpray": [ "Dagger Spray", "DaggerSpray", "匕首雨" ],
    "StS2 Silent-DaggerSprayPlus": [ "Dagger Spray+", "DaggerSpray+", "匕首雨+" ],
    "StS2 Silent-DaggerThrow": [ "Dagger Throw", "DaggerThrow", "投掷匕首" ],
    "StS2 Silent-DaggerThrowPlus": [ "Dagger Throw+", "DaggerThrow+", "投掷匕首+" ],
    "StS2 Silent-Dash": [ "Dash", "冲刺" ],
    "StS2 Silent-DashPlus": [ "Dash+", "冲刺+" ],
    "StS2 Silent-DeadlyPoison": [ "Deadly Poison", "DeadlyPoison", "致命毒药" ],
    "StS2 Silent-DeadlyPoisonPlus": [ "Deadly Poison+", "DeadlyPoison+", "致命毒药+" ],
    "StS2 Silent-Defend": [ "Defend", "防御" ],
    "StS2 Silent-DefendPlus": [ "Defend+", "防御+" ],
    "StS2 Silent-Deflect": [ "Deflect", "偏折" ],
    "StS2 Silent-DeflectPlus": [ "Deflect+", "偏折+" ],
    "StS2 Silent-DodgeandRoll": [ "Dodge and Roll", "DodgeandRoll", "闪躲翻滚" ],
    "StS2 Silent-DodgeandRollPlus": [ "Dodge and Roll+", "DodgeandRoll+", "闪躲翻滚+" ],
    "StS2 Silent-EchoingSlash": [ "Echoing Slash", "EchoingSlash", "回响斩击" ],
    "StS2 Silent-EchoingSlashPlus": [ "Echoing Slash+", "EchoingSlash+", "回响斩击+" ],
    "StS2 Silent-Envenom": [ "Envenom", "涂毒" ],
    "StS2 Silent-EnvenomPlus": [ "Envenom+", "涂毒+" ],
    "StS2 Silent-EscapePlan": [ "Escape Plan", "EscapePlan", "逃脱计划" ],
    "StS2 Silent-EscapePlanPlus": [ "Escape Plan+", "EscapePlan+", "逃脱计划+" ],
    "StS2 Silent-Expertise": [ "Expertise", "独门技术" ],
    "StS2 Silent-ExpertisePlus": [ "Expertise+", "独门技术+" ],
    "StS2 Silent-Expose": [ "Expose", "暴露" ],
    "StS2 Silent-ExposePlus": [ "Expose+", "暴露+" ],
    "StS2 Silent-FanOfKnives": [ "Fan of Knives", "FanofKnives", "刀扇" ],
    "StS2 Silent-FanOfKnivesPlus": [ "Fan of Knives+", "FanofKnives+", "刀扇+" ],
    "StS2 Silent-Finisher": [ "Finisher", "终结技" ],
    "StS2 Silent-FinisherPlus": [ "Finisher+", "终结技+" ],
    "StS2 Silent-Flanking": [ "Flanking", "夹击" ],
    "StS2 Silent-FlankingPlus": [ "Flanking+", "夹击+" ],
    "StS2 Silent-Flechettes": [ "Flechettes", "飞镖" ],
    "StS2 Silent-FlechettesPlus": [ "Flechettes+", "飞镖+" ],
    "StS2 Silent-FlickFlack": [ "Flick-Flack", "FlickFlack", "翻越撑击" ],
    "StS2 Silent-FlickFlackPlus": [ "Flick-Flack+", "FlickFlack+", "翻越撑击+" ],
    "StS2 Silent-FollowThrough": [ "Follow Through", "FollowThrough", "跟进" ],
    "StS2 Silent-FollowThroughPlus": [ "Follow Through+", "FollowThrough+", "跟进+" ],
    "StS2 Silent-Footwork": [ "Footwork", "灵动步法" ],
    "StS2 Silent-FootworkPlus": [ "Footwork+", "灵动步法+" ],
    "StS2 Silent-GrandFinale": [ "Grand Finale", "GrandFinale", "华丽收场" ],
    "StS2 Silent-GrandFinalePlus": [ "Grand Finale+", "GrandFinale+", "华丽收场+" ],
    "StS2 Silent-HandTrick": [ "Hand Trick", "HandTrick", "手上技法" ],
    "StS2 Silent-HandTrickPlus": [ "Hand Trick+", "HandTrick+", "手上技法+" ],
    "StS2 Silent-Haze": [ "Haze", "迷雾" ],
    "StS2 Silent-HazePlus": [ "Haze+", "迷雾+" ],
    "StS2 Silent-HiddenDaggers": [ "Hidden Daggers", "HiddenDaggers", "隐秘匕首" ],
    "StS2 Silent-HiddenDaggersPlus": [ "Hidden Daggers+", "HiddenDaggers+", "隐秘匕首+" ],
    "StS2 Silent-InfiniteBlades": [ "Infinite Blades", "InfiniteBlades", "无尽刀刃" ],
    "StS2 Silent-InfiniteBladesPlus": [ "Infinite Blades+", "InfiniteBlades+", "无尽刀刃+" ],
    "StS2 Silent-KnifeTrap": [ "Knife Trap", "KnifeTrap", "刀刃陷阱" ],
    "StS2 Silent-KnifeTrapPlus": [ "Knife Trap+", "KnifeTrap+", "刀刃陷阱+" ],
    "StS2 Silent-LeadingStrike": [ "Leading Strike", "LeadingStrike", "先制打击" ],
    "StS2 Silent-LeadingStrikePlus": [ "Leading Strike+", "LeadingStrike+", "先制打击+" ],
    "StS2 Silent-LegSweep": [ "Leg Sweep", "LegSweep", "扫腿" ],
    "StS2 Silent-LegSweepPlus": [ "Leg Sweep+", "LegSweep+", "扫腿+" ],
    "StS2 Silent-Malaise": [ "Malaise", "萎靡" ],
    "StS2 Silent-MalaisePlus": [ "Malaise+", "萎靡+" ],
    "StS2 Silent-MasterPlanner": [ "Master Planner", "MasterPlanner", "谋划专家" ],
    "StS2 Silent-MasterPlannerPlus": [ "Master Planner+", "MasterPlanner+", "谋划专家+" ],
    "StS2 Silent-MementoMori": [ "Memento Mori", "MementoMori", "铭记死亡" ],
    "StS2 Silent-MementoMoriPlus": [ "Memento Mori+", "MementoMori+", "铭记死亡+" ],
    "StS2 Silent-Mirage": [ "Mirage", "蜃景" ],
    "StS2 Silent-MiragePlus": [ "Mirage+", "蜃景+" ],
    "StS2 Silent-Murder": [ "Murder", "谋杀" ],
    "StS2 Silent-MurderPlus": [ "Murder+", "谋杀+" ],
    "StS2 Silent-Neutralize": [ "Neutralize", "中和" ],
    "StS2 Silent-NeutralizePlus": [ "Neutralize+", "中和+" ],
    "StS2 Silent-Nightmare": [ "Nightmare", "夜魇" ],
    "StS2 Silent-NightmarePlus": [ "Nightmare+", "夜魇+" ],
    "StS2 Silent-NoxiousFumes": [ "Noxious Fumes", "NoxiousFumes", "毒雾" ],
    "StS2 Silent-NoxiousFumesPlus": [ "Noxious Fumes+", "NoxiousFumes+", "毒雾+" ],
    "StS2 Silent-Outbreak": [ "Outbreak", "毒性爆发" ],
    "StS2 Silent-OutbreakPlus": [ "Outbreak+", "毒性爆发+" ],
    "StS2 Silent-PhantomBlades": [ "Phantom Blades", "PhantomBlades", "幻影之刃" ],
    "StS2 Silent-PhantomBladesPlus": [ "Phantom Blades+", "PhantomBlades+", "幻影之刃+" ],
    "StS2 Silent-PiercingWail": [ "Piercing Wail", "PiercingWail", "尖啸" ],
    "StS2 Silent-PiercingWailPlus": [ "Piercing Wail+", "PiercingWail+", "尖啸+" ],
    "StS2 Silent-Pinpoint": [ "Pinpoint", "精密瞄准" ],
    "StS2 Silent-PinpointPlus": [ "Pinpoint+", "精密瞄准+" ],
    "StS2 Silent-PoisonedStab": [ "Poisoned Stab", "PoisonedStab", "带毒刺击" ],
    "StS2 Silent-PoisonedStabPlus": [ "Poisoned Stab+", "PoisonedStab+", "带毒刺击+" ],
    "StS2 Silent-Pounce": [ "Pounce", "猛扑" ],
    "StS2 Silent-PouncePlus": [ "Pounce+", "猛扑+" ],
    "StS2 Silent-PreciseCut": [ "Precise Cut", "PreciseCut", "精确切击" ],
    "StS2 Silent-PreciseCutPlus": [ "Precise Cut+", "PreciseCut+", "精确切击+" ],
    "StS2 Silent-Predator": [ "Predator", "猎杀者" ],
    "StS2 Silent-PredatorPlus": [ "Predator+", "猎杀者+" ],
    "StS2 Silent-Prepared": [ "Prepared", "早有准备" ],
    "StS2 Silent-PreparedPlus": [ "Prepared+", "早有准备+" ],
    "StS2 Silent-Reflex": [ "Reflex", "本能反应" ],
    "StS2 Silent-ReflexPlus": [ "Reflex+", "本能反应+" ],
    "StS2 Silent-Ricochet": [ "Ricochet", "连续反弹" ],
    "StS2 Silent-RicochetPlus": [ "Ricochet+", "连续反弹+" ],
    "StS2 Silent-Scare": [ "Scare", "恫吓" ],
    "StS2 Silent-ScarePlus": [ "Scare+", "恫吓+" ],
    "StS2 Silent-SerpentForm": [ "Serpent Form", "SerpentForm", "群蛇形态" ],
    "StS2 Silent-SerpentFormPlus": [ "Serpent Form+", "SerpentForm+", "群蛇形态+" ],
    "StS2 Silent-Shadowmeld": [ "Shadowmeld", "融入暗影" ],
    "StS2 Silent-ShadowmeldPlus": [ "Shadowmeld+", "融入暗影+" ],
    "StS2 Silent-ShadowStep": [ "Shadow Step", "ShadowStep", "暗影步" ],
    "StS2 Silent-ShadowStepPlus": [ "Shadow Step+", "ShadowStep+", "暗影步+" ],
    "StS2 Silent-Sidestep": [ "Sidestep", "侧步" ],
    "StS2 Silent-SidestepPlus": [ "Sidestep+", "侧步+" ],
    "StS2 Silent-Skewer": [ "Skewer", "串刺" ],
    "StS2 Silent-SkewerPlus": [ "Skewer+", "串刺+" ],
    "StS2 Silent-Slice": [ "Slice", "切割" ],
    "StS2 Silent-SlicePlus": [ "Slice+", "切割+" ],
    "StS2 Silent-Snakebite": [ "Snakebite", "蛇咬" ],
    "StS2 Silent-SnakebitePlus": [ "Snakebite+", "蛇咬+" ],
    "StS2 Silent-Sneaky": [ "Sneaky", "鬼祟" ],
    "StS2 Silent-SneakyPlus": [ "Sneaky+", "鬼祟+" ],
    "StS2 Silent-Speedster": [ "Speedster", "速行者" ],
    "StS2 Silent-SpeedsterPlus": [ "Speedster+", "速行者+" ],
    "StS2 Silent-StormOfSteel": [ "Storm of Steel", "StormofSteel", "钢铁风暴" ],
    "StS2 Silent-StormOfSteelPlus": [ "Storm of Steel+", "StormofSteel+", "钢铁风暴+" ],
    "StS2 Silent-Strangle": [ "Strangle", "紧勒" ],
    "StS2 Silent-StranglePlus": [ "Strangle+", "紧勒+" ],
    "StS2 Silent-Strike": [ "Strike", "打击" ],
    "StS2 Silent-StrikePlus": [ "Strike+", "打击+" ],
    "StS2 Silent-SuckerPunch": [ "Sucker Punch", "SuckerPunch", "突然一拳" ],
    "StS2 Silent-SuckerPunchPlus": [ "Sucker Punch+", "SuckerPunch+", "突然一拳+" ],
    "StS2 Silent-Suppress": [ "Suppress", "压制" ],
    "StS2 Silent-SuppressPlus": [ "Suppress+", "压制+" ],
    "StS2 Silent-Survivor": [ "Survivor", "生存者" ],
    "StS2 Silent-SurvivorPlus": [ "Survivor+", "生存者+" ],
    "StS2 Silent-Tactician": [ "Tactician", "战术大师" ],
    "StS2 Silent-TacticianPlus": [ "Tactician+", "战术大师+" ],
    "StS2 Silent-TheHunt": [ "The Hunt", "TheHunt", "狩猎" ],
    "StS2 Silent-TheHuntPlus": [ "The Hunt+", "TheHunt+", "狩猎+" ],
    "StS2 Silent-ToolsOfTheTrade": [ "Tools of the Trade", "ToolsoftheTrade", "必备工具" ],
    "StS2 Silent-ToolsOfTheTradePlus": [ "Tools of the Trade+", "ToolsoftheTrade+", "必备工具+" ],
    "StS2 Silent-Tracking": [ "Tracking", "跟踪" ],
    "StS2 Silent-TrackingPlus": [ "Tracking+", "跟踪+" ],
    "StS2 Silent-Untouchable": [ "Untouchable", "触不可及" ],
    "StS2 Silent-UntouchablePlus": [ "Untouchable+", "触不可及+" ],
    "StS2 Silent-UpMySleeve": [ "Up My Sleeve", "UpMySleeve", "袖里乾坤" ],
    "StS2 Silent-UpMySleevePlus": [ "Up My Sleeve+", "UpMySleeve+", "袖里乾坤+" ],
    "StS2 Silent-WellLaidPlans": [ "Well-Laid Plans", "WellLaidPlans", "计划妥当" ],
    "StS2 Silent-WellLaidPlansPlus": [ "Well-Laid Plans+", "WellLaidPlans+", "计划妥当+" ],
    "StS2 Silent-WraithForm": [ "Wraith Form", "WraithForm", "幽魂形态" ],
    "StS2 Silent-WraithFormPlus": [ "Wraith Form+", "WraithForm+", "幽魂形态+" ],
}
